from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, Flowable

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'output'/'pdf'/'VeriClaim_Deep_Learning_and_Ensemble_Engineering_Book_V3.pdf'
NAVY=colors.HexColor('#102A43'); TEAL=colors.HexColor('#087E8B'); MINT=colors.HexColor('#DFF4F0'); PALE=colors.HexColor('#F5F8FA'); INK=colors.HexColor('#172B4D'); MUTED=colors.HexColor('#52616B')

class Diagram(Flowable):
    def __init__(self,labels,caption): super().__init__(); self.labels=labels; self.caption=caption; self.width=17*cm; self.height=4*cm
    def draw(self):
        c=self.canv; c.setFillColor(PALE); c.roundRect(0,0,self.width,self.height,10,fill=1,stroke=0); n=len(self.labels); w=3*cm; gap=(self.width-n*w)/(n+1)
        for i,label in enumerate(self.labels):
            x=gap+i*(w+gap); c.setFillColor(MINT); c.setStrokeColor(TEAL); c.roundRect(x,1.6*cm,w,1.1*cm,7,fill=1,stroke=1); c.setFillColor(NAVY); c.setFont('Helvetica-Bold',7)
            for j,line in enumerate(label.split('\n')): c.drawCentredString(x+w/2,2.25*cm-j*.25*cm,line)
            if i<n-1: c.setStrokeColor(TEAL); c.line(x+w,2.15*cm,x+w+gap,2.15*cm); c.setFillColor(TEAL); c.circle(x+w+gap,2.15*cm,2,fill=1,stroke=0)
        c.setFillColor(MUTED); c.setFont('Helvetica-Oblique',7); c.drawCentredString(self.width/2,.5*cm,self.caption)

def header(c,doc):
    c.saveState()
    if doc.page>1:
        c.setStrokeColor(colors.HexColor('#D7E2E8')); c.line(1.7*cm,28.2*cm,19.3*cm,28.2*cm); c.line(1.7*cm,1.45*cm,19.3*cm,1.45*cm); c.setFillColor(MUTED); c.setFont('Helvetica',8); c.drawString(1.7*cm,28.45*cm,'VERICLAIM AI - ENGINEERING ROLE STUDY GUIDE'); c.drawRightString(19.3*cm,1.15*cm,f'Page {doc.page}')
    c.restoreState()

def build():
    OUT.parent.mkdir(parents=True,exist_ok=True); ss=getSampleStyleSheet()
    title=ParagraphStyle('t',parent=ss['Title'],fontName='Helvetica-Bold',fontSize=27,leading=33,textColor=NAVY,alignment=TA_CENTER)
    sub=ParagraphStyle('s',parent=ss['Normal'],fontName='Helvetica',fontSize=12,leading=17,textColor=MUTED,alignment=TA_CENTER)
    h1=ParagraphStyle('h1',parent=ss['Heading1'],fontName='Helvetica-Bold',fontSize=18,leading=23,textColor=NAVY,spaceBefore=8,spaceAfter=8)
    h2=ParagraphStyle('h2',parent=ss['Heading2'],fontName='Helvetica-Bold',fontSize=12.4,leading=16,textColor=TEAL,spaceBefore=8,spaceAfter=4)
    body=ParagraphStyle('b',parent=ss['BodyText'],fontName='Helvetica',fontSize=9.1,leading=13.2,textColor=INK,spaceAfter=5)
    bullet=ParagraphStyle('bl',parent=body,leftIndent=15,firstLineIndent=-10,bulletIndent=2,spaceAfter=3)
    call=ParagraphStyle('c',parent=body,backColor=MINT,borderColor=TEAL,borderWidth=.7,borderPadding=8,spaceBefore=4,spaceAfter=8)
    small=ParagraphStyle('sm',parent=body,fontSize=7.8,leading=10,textColor=MUTED)
    P=lambda x,s=body,**kw:Paragraph(x,s,**kw); B=lambda x:P(x,bullet,bulletText='-')
    story=[Spacer(1,3.2*cm),P('VERICLAIM AI',ParagraphStyle('k',parent=sub,fontName='Helvetica-Bold',fontSize=12,textColor=TEAL)),Spacer(1,.2*cm),P('Deep Learning and Ensemble Engineering',title),P('A chapter-based project textbook: CNN foundations, hybrid ensembles and evaluation',sub),Spacer(1,.65*cm)]
    intro=Table([[P('<b>Part II: Deep Learning</b><br/>EfficientNetV2B0 preprocessing, frozen transfer learning, CNN fraud heads, augmentation experiments and CNN evaluation.',body),P('<b>Part III: Ensemble Learning</b><br/>Extra Trees, MLP, archive similarity, stacking, calibration, thresholds, model comparison and dashboard metrics.',body)]],colWidths=[8.15*cm,8.15*cm])
    intro.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),MINT),('BOX',(0,0),(-1,-1),.8,TEAL),('INNERGRID',(0,0),(-1,-1),.35,TEAL),('VALIGN',(0,0),(-1,-1),'TOP'),('TOPPADDING',(0,0),(-1,-1),12),('BOTTOMPADDING',(0,0),(-1,-1),12),('LEFTPADDING',(0,0),(-1,-1),12)])); story += [intro,Spacer(1,.55*cm),P('How to use this guide',h2),P('Study your own part deeply, then read the other part well enough to explain how both roles connect. The best team members know their boundary and the full end-to-end data flow.',call),PageBreak()]
    def section(title_,why,parts,diagram=None,checkpoint=None):
        chapter_titles = {
            'Part I - Shared foundation': 'Chapter 1 - Shared project foundation',
            'Role 3 - Deep-Learning Engineer: ownership map': 'Chapter 2 - EfficientNet system map',
            'Role 3.1 - Image preprocessing exactly': 'Chapter 3 - Image preprocessing exactly',
            'Role 3.2 - Transfer learning and EfficientNetV2B0': 'Chapter 4 - Transfer learning and EfficientNetV2B0',
            'Role 3.3 - CNN fraud head and weighted learning': 'Chapter 5 - CNN fraud head and weighted learning',
            'Role 3.4 - Data augmentation experiments': 'Chapter 6 - Data augmentation experiments',
            'Role 3.5 - CNN dashboard and reviewer explanation': 'Chapter 7 - CNN dashboard and reviewer explanation',
            'Role 4 - ML and Ensemble Engineer: ownership map': 'Chapter 8 - Ensemble system map',
            'Role 4.1 - Extra Trees from first principles': 'Chapter 9 - Extra Trees from first principles',
            'Role 4.2 - MLP and feature diversity': 'Chapter 10 - MLP and feature diversity',
            'Role 4.3 - Archive similarity and pHash': 'Chapter 11 - Archive similarity and pHash',
            'Role 4.4 - Stacking without leakage': 'Chapter 12 - Stacking without leakage',
            'Role 4.5 - Calibration and threshold selection': 'Chapter 13 - Calibration and threshold selection',
            'Role 4.6 - Comparison dashboard and release checklist': 'Chapter 14 - Comparison dashboard and release checklist',
            'Role 3 and Role 4 - joint 10-day learning plan': 'Chapter 15 - Joint 10-day learning plan',
            'Deep-learning lab manual: build confidence step by step': 'Chapter 16 - Deep-learning laboratory manual',
            'CNN architecture explained visually': 'Chapter 17 - CNN architecture explained visually',
            'Fine-tuning decision framework': 'Chapter 18 - Fine-tuning decision framework',
            'Ensemble lab manual: build confidence step by step': 'Chapter 19 - Ensemble laboratory manual',
            'Probability, calibration and threshold workshop': 'Chapter 20 - Probability, calibration and threshold workshop',
            'Model comparison dashboard specification': 'Chapter 21 - Model comparison dashboard specification',
            'Joint integration, regression testing and release': 'Chapter 22 - Joint integration, regression testing and release',
            'Reviewer-ready Q&A for each role': 'Chapter 23 - Reviewer-ready Q&A',
        }
        title_ = chapter_titles.get(title_, title_)
        story.append(P(title_,h1)); story.append(P(f'<b>Why this matters:</b> {why}',body));
        if diagram: story.extend([diagram,Spacer(1,.15*cm)])
        for heading,items in parts:
            story.append(P(heading,h2))
            for item in items: story.append(B(item[2:]) if item.startswith('- ') else P(item,body))
        if checkpoint: story.append(P(f'<b>Mastery checkpoint:</b> {checkpoint}',call))
        story.append(Spacer(1,.22*cm))
    section('Part I - Shared foundation','Both roles must agree on the problem, data, validation protocol and success criteria.',[("The shared task",["The target is binary: fraud = 1 and non-fraud = 0. The model recommends human review; it never establishes a customer committed fraud.","Training set: 5,200 images, including 200 fraud and 5,000 non-fraud. This 3.85% fraud rate makes ordinary accuracy misleading."]),("The shared pipeline",["The Deep-Learning Engineer turns a photo into a robust CNN embedding. The Ensemble Engineer combines that embedding-derived score with tree, MLP and archive-similarity scores.","Both roles must use the same train/test boundaries, duplicate-aware groups, saved artifact version and evaluation report."]),("Shared success measures",["Primary: fraud recall, precision, F1, F2, PR AUC, calibration and review workload. Supporting: accuracy, balanced accuracy and ROC AUC.","Never call a model 'better' merely because accuracy increased. Verify whether it also improves precision-recall behavior on an honest validation protocol."])],Diagram(['Claim image','CNN embedding','Base-model scores','Fusion','Human review'],'The roles meet at the embedding, validation and final-calibrated-probability interfaces.'),'Explain why a 96% accuracy model could still be useless when fraud is rare.')
    section('Role 3 - Deep-Learning Engineer: ownership map','Your responsibility is to produce reliable visual representations and an independently evaluated CNN fraud signal.',[("Deliverables",["A reproducible EfficientNetV2B0 preprocessing and embedding pipeline.","Saved backbone artifact: models/efficientnet_hybrid/efficientnetv2b0_backbone.keras.","CNN-head probabilities evaluated separately from the hybrid.","An augmentation experiment log with settings, grouped-validation metrics and visual sanity checks.","A concise neural-network architecture explanation for the team and judges."]),("Core project file",["Read src/vericlaim/train_efficientnet_hybrid.py. The key functions are extract_embeddings and fit_cnn_head.","The script creates EfficientNetV2B0(include_top=False, weights='imagenet', pooling='avg', include_preprocessing=True) and sets backbone.trainable = False."])])
    section('Role 3.1 - Image preprocessing exactly','Preprocessing is part of the model. A correct CNN can still fail if training and website preparation differ.',[("What happens in this project",["tf.io.read_file reads the file. tf.io.decode_image converts it to a three-channel RGB tensor. image.set_shape([None, None, 3]) gives TensorFlow a known channel shape.","tf.image.resize_with_pad produces a square 224 x 224 image without stretching the original aspect ratio. It pads unused space instead of squeezing a wide or tall vehicle photo.","The image becomes float32. EfficientNetV2B0 is created with include_preprocessing=True, so its built-in preprocessing expects raw float pixel values."]),("Why batching and caching matter",["The pipeline maps image decoding in parallel, batches 32 images, then prefetches the next batch while the GPU/CPU works. This improves throughput without changing predictions.","Embeddings are cached with version, paths and image size. Reuse is safe only when all three match; otherwise stale features can silently corrupt experiments."]),("Checks to run",["Open a sample of resized/padded images. Ensure a damaged area has not been cropped away, colors are not swapped and corrupted files fail clearly.","Run the same image through the training extraction function and the website inference path. The embedding shape and preprocessing behavior must match."])],None,'You can explain why resize_with_pad is safer than blindly stretching every photo to a square.')
    section('Role 3.2 - Transfer learning and EfficientNetV2B0','Transfer learning gives a small fraud dataset a strong visual starting point.',[("What is transferred",["ImageNet pretraining supplies general visual filters: edges, colors, textures, shapes and object fragments. It does not supply insurance-fraud labels.","EfficientNetV2B0 outputs a 1,280-number embedding after global average pooling. This is a compact visual summary used by the CNN head and the hybrid system."]),("Why the backbone is frozen",["With only 200 fraud images, training all EfficientNet weights could overfit badly. Freezing keeps general visual features stable and trains smaller fraud-specific heads on top.","Frozen does not mean useless: the backbone still performs sophisticated feature extraction. It means its millions of ImageNet-derived weights are not updated in this run."]),("Future fine-tuning experiment",["After establishing a grouped-validation baseline, unfreeze only the final EfficientNet blocks, use a very small learning rate, early stopping and strict leakage-aware folds.","Compare CNN standalone PR AUC, recall, calibration and false-negative examples. Keep the frozen version if fine-tuning does not improve all relevant outcomes."])],None,'State clearly: ImageNet provides generic visual knowledge; supplied project images train fraud-specific heads.')
    section('Role 3.3 - CNN fraud head and weighted learning','The CNN embedding still needs a classifier that learns the fraud/non-fraud decision boundary.',[("Current head",["fit_cnn_head uses LogisticRegression(C=0.35, class_weight='balanced', max_iter=2500). A sigmoid Dense(1) neural head is mathematically equivalent to logistic regression over the embedding.","The project trains one CNN head per fold. Each head scores validation images it did not train on, producing out-of-fold CNN probabilities."]),("Why class_weight balanced",["Fraud examples are rare. class_weight='balanced' increases minority-class contribution automatically based on class frequency, preventing the head from learning the easy 'always non-fraud' solution.","This is separate from the MLP's explicit fraud weighting and the rotating tree balancing. Explain each component accurately rather than calling all of them 'oversampling'."]),("CNN evaluation",["Report standalone CNN metrics before fusion. If the hybrid improves, you should be able to show what each model contributed rather than hiding poor components.","Inspect CNN false negatives and false positives. A high final hybrid score can hide a CNN weakness that becomes important on future data."])])
    section('Role 3.4 - Data augmentation experiments','Augmentation can improve robustness, but it is a controlled experiment, not automatically a benefit.',[("Safe candidates",["Mild brightness and contrast variation can simulate different phone cameras and lighting. Small rotation may handle angle variation. Conservative crop/zoom can reduce framing sensitivity.","Apply augmentation only inside each training fold. Never augment test or validation images, and never create a transformed version that crosses from training into validation."]),("Dangerous transformations",["Large rotations can make vehicle damage physically implausible. Aggressive crops can remove the damage context. Strong color changes can create artificial fraud cues. Horizontal flips may be questionable if side-specific vehicle context matters.","Do not claim augmentation was used unless it is present in the active training pipeline and evaluated. Current production artifact should be described as class-weighted and rotation-balanced; augmentation is an experiment unless validated and integrated."]),("Experiment table",["For every policy record: exact transforms, probability, seed, folds, runtime, standalone CNN PR AUC, hybrid PR AUC, recall, precision, calibration and qualitative image examples.","Accept an augmentation policy only if it improves grouped validation without creating implausible training images or degrading real review workload."])],None,'Explain why augmentation and class weighting solve different problems.')
    section('Role 3.5 - CNN dashboard and reviewer explanation','Your dashboard should turn neural-network behavior into evidence a non-expert can understand.',[("Recommended CNN panel",["Show backbone name, frozen/fine-tuned status, input size 224 x 224, embedding dimension 1,280, number of fold heads, class balancing method and model artifact version.","Show standalone CNN metrics and a confusion matrix. Make clear whether metrics come from out-of-fold validation or supplied test data."]),("Explainability roadmap",["Add Grad-CAM only as a future validated capability. It can highlight regions influential to a CNN score but is not proof the model reasoned correctly.","Add an out-of-distribution warning when an uploaded image is unlike training images. This is especially useful for unrelated tire photos or unusual photographic styles."])])
    section('Role 4 - ML and Ensemble Engineer: ownership map','Your responsibility is to build reliable complementary signals, combine them without leakage, calibrate results and expose a defensible threshold.',[("Deliverables",["Full-data Extra Trees models, rotating balanced Extra Trees models, MLP models and archive-similarity signals.","Out-of-fold base-model predictions, stacking inputs, logistic fusion model and Platt calibration model.","Threshold selection report, model comparison table and performance dashboard.","A release decision note that explains recall, precision, workload and limitations."]),("Core interfaces",["The Ensemble Engineer receives x_train/x_test existing features, cnn_train/cnn_test embeddings or CNN scores, perceptual hashes and binary labels.","The output is vericlaim_model.joblib containing base models, stacker, calibrator, thresholds, reference hashes, reference labels and metrics."])])
    section('Role 4.1 - Extra Trees from first principles','Extra Trees are randomized decision-tree ensembles. They capture patterns differently from neural networks.',[("How one tree works",["A tree asks feature questions such as 'is feature 87 greater than a split value?' and continues down branches until it reaches a leaf with a class distribution.","One tree can overfit. A forest averages many randomized trees, reducing variance and creating a smoother probability estimate."]),("Current full-data forest",["For each fold the script builds ExtraTreesClassifier(n_estimators=300, min_samples_leaf=2, max_features=0.20, class_weight='balanced_subsample').", "balanced_subsample balances class contribution within each tree's bootstrap-like sampling. min_samples_leaf=2 avoids leaves based on one example. max_features=0.20 adds feature diversity among trees."]),("Current rotating forests",["fit_balanced_subset_models receives every fraud example and different normal subsets at ratio 1:8. Across five folds, the models are accumulated in balanced_models.","Average their probabilities. This prevents one learner from being flooded by normal examples while preserving broad normal coverage across the ensemble."])],None,'Explain why tree diversity is helpful: many imperfect diverse trees average into a more stable model.')
    section('Role 4.2 - MLP and feature diversity','The MLP uses the existing non-CNN feature representation, while the CNN uses learned visual embedding and Extra Trees use randomized split rules.',[("Why retain an MLP",["An MLP can discover smooth non-linear combinations in engineered features. Its errors may differ from tree and CNN errors, which is valuable for a hybrid ensemble.","fit_neural_model is called once per validation fold. Keep its training seed, architecture and weighting documented in the model report."]),("Avoid redundant models",["An ensemble improves only if members provide complementary information. If every model makes the same mistakes, averaging adds complexity without value.","Track correlation between out-of-fold model scores and overlap between false positives/false negatives. Low-to-moderate correlation can indicate useful diversity."]),("Ablation test",["Compare full hybrid against versions without CNN, without archive similarity, without rotating trees and without MLP. Report deltas in PR AUC, recall, precision and calibration.","Ablation is the strongest way to prove each module earns its place."])])
    section('Role 4.3 - Archive similarity and pHash','Similarity is a separate evidence source, not a simple duplicate detector.',[("Perceptual hashes",["pHash creates a short visual signature so similar images tend to have nearby hash values. Hamming distance counts how many bits differ between hashes.","archive_similarity_features compares a query hash with labelled training hashes and creates fraud-archive and legitimate-archive similarity signals."]),("Why both fraud and legitimate archives",["A close fraud match may raise concern, while a close legitimate match may lower it. The stack_features function includes both and also their difference: fraud similarity minus legitimate similarity.","This avoids treating all visual similarity as suspicious. A claim may be visually similar to normal examples for a perfectly legitimate reason."]),("Review experience",["Show similarity as supporting evidence: close match count, distance or example references where permitted. Do not state 'duplicate fraud' from a pHash score alone.","Use pHash both for archive signal and for perceptual grouping in validation. These are related but distinct uses."])])
    section('Role 4.4 - Stacking without leakage','Stacking is powerful only when the fusion model learns from honest base-model predictions.',[("The wrong approach",["Train a base model on every training image, predict the same training image, then train a stacker on those overly optimistic predictions. The stacker learns a fantasy performance level.","This is leakage even when no test label was directly used."]),("The correct project approach",["StratifiedGroupKFold creates five fit/validation partitions. For a fold, base models train on fit_indices and predict validation_indices. Those predictions fill oof_full, oof_balanced, oof_neural and oof_cnn.","oof_archive is created by comparing each validation hash only against hashes from fit_indices, never its own validation set. This prevents a direct self-match signal.","The logistic meta model creates oof_raw scores using the same fold discipline. Then the final stacker is fit on all out-of-fold stacked features for deployment."]),("Stack features",["stack_features returns: full tree score, rotating tree score, MLP score, CNN score, fraud archive score, legitimate archive score and their difference.","The stacker uses class_weight='balanced' and C=10.0. Treat these as hyperparameters to document, not magic constants."])],Diagram(['Fold A fit','Fold A base\npredictions','OOF stack\nrows','Meta model','Calibrated score'],'Out-of-fold predictions keep every training row honest for stacking and calibration.'),'Be able to define stacking leakage with an example.')
    section('Role 4.5 - Calibration and threshold selection','A raw model score is not automatically a trustworthy probability. Calibration and thresholding turn scores into an operational triage policy.',[("Platt calibration",["The calibrator is LogisticRegression(C=1000.0) trained on out-of-fold raw stacker scores. It learns a sigmoid mapping from raw score to calibrated probability.","Calibration should be assessed with Brier score, reliability curves and observed fraud rate by score band. A calibrated 0.20 should correspond roughly to 20% fraud prevalence in comparable data, subject to sample size."]),("Three thresholds",["choose_threshold returns review and investigate thresholds using a recall target. choose_classification_threshold returns a classification-oriented threshold. The saved report exposes review, classification and investigate values.","The website's active label must clearly state which threshold it uses. In the current configuration the review threshold is 0.0612; its low value reflects recall-first triage rather than a declaration of guilt."]),("Capacity-aware policy",["If staff can review 100 cases a day, evaluate how many flags each threshold creates. Choose the threshold using fraud recall, precision and human capacity together.","When a threshold changes, do not say the model changed. The scoring model can stay fixed while the operating policy changes."])],None,'Explain the difference: calibration makes scores interpretable; thresholding converts an interpretable score into an action rule.')
    section('Role 4.6 - Comparison dashboard and release checklist','Your dashboard makes evidence visible to the whole team and to judges.',[("Required comparison view",["Rows: previous MLP hybrid, CNN standalone, full Extra Trees, rotating trees, full hybrid. Columns: accuracy, balanced accuracy, precision, recall, F1, F2, ROC AUC, PR AUC, Brier score, threshold, false positives, false negatives and runtime.","Label each result by evaluation source: out-of-fold validation or supplied test split. Never mix them in the same column without clear labeling."]),("Current key comparison",["Previous MLP hybrid: accuracy 83.33%, recall 81.72%, precision 25.76%, PR AUC 0.6438.","Current EfficientNet hybrid: accuracy 96.12%, recall 92.47%, precision 64.18%, F1 75.77%, F2 84.98%, ROC AUC 0.9759 and PR AUC 0.9048 on the supplied test split.","Current supplied-test confusion matrix: 1,275 true negatives, 48 false positives, 7 false negatives and 86 true positives."]),("Release checklist",["Confirm the artifact, backbone and metric JSON were produced in the same run. Verify the website loads them. Run known example uploads. Inspect errors. Document leakage caveat.","Do not promote a model solely because one metric improved. Require no regression in chosen safety metrics and a clear business reason for any trade-off."])])
    section('Role 3 and Role 4 - joint 10-day learning plan','The two roles should meet daily because feature extraction, evaluation and output behavior are shared responsibilities.',[("Days 1-2",["Role 3: run preprocessing on samples and explain 224 x 224 padding, embedding and frozen transfer learning. Role 4: inspect class counts, existing features and pHash signals."]),("Days 3-4",["Role 3: explain CNN head and class weights; create an augmentation proposal. Role 4: explain Extra Trees, rotating ratio 1:8 and MLP diversity."]),("Days 5-6",["Together: trace one fold of train_efficientnet_hybrid.py from fit indices to out-of-fold predictions. Draw the no-leakage stacking diagram."]),("Days 7-8",["Role 3: evaluate CNN standalone. Role 4: run ablation/comparison table and threshold capacity analysis. Review false positives and false negatives together."]),("Days 9-10",["Together: test Model Lab, rehearse the two-minute explanation and answer reviewer questions about imbalance, ImageNet, pHash, leakage, calibration and customer safety."])],None,'Each engineer can explain their own part in detail and the other part at a high level.')
    story.append(PageBreak())
    section('Deep-learning lab manual: build confidence step by step','Role 3 should be able to prove that the CNN pipeline is correct before arguing that it is accurate.',[("Lab A - preprocess one image",["Choose one known training photo. Print original width, height, channel count and file format. Run decode plus resize_with_pad. Save a temporary visualization for inspection.","Expected result: three channels, 224 x 224 output, no stretching, and the damage region still visible. If the damage disappears due to padding/crop behavior, stop and investigate before training."]),("Lab B - verify embeddings",["Run extract_embeddings twice using the same image paths, image size and backbone. The first run builds the cache; the second should reuse it. Confirm shape is number_of_images by 1,280.","Change image size or cache version deliberately and verify a new cache is produced. This teaches why cache metadata is a safety feature, not an optimization only."]),("Lab C - evaluate the CNN head",["Use the fold-held-out CNN probabilities, not training probabilities. Calculate threshold-specific confusion matrix, recall, precision, F1, PR AUC and Brier score.","Write down three CNN false negatives and three false positives. Inspect them visually and describe what is difficult without claiming the image proves a causal reason."]),("Lab D - augmentation trial",["Make one conservative policy: brightness/contrast jitter plus small rotation. Create a visual contact sheet of ten transformed images and reject any unrealistic transformation.","Train under the exact same grouped folds. Keep the policy only if it improves validation behavior without degraded calibration or implausible visual evidence."])],Diagram(['Original image','Decode RGB','Resize with pad','EfficientNet','1,280 embedding','CNN head'],'Role 3 validates every arrow before handing CNN probabilities to the ensemble.'),'You can reproduce the CNN path for a single image and explain every tensor transformation.')
    section('CNN architecture explained visually','This section gives Role 3 the language to explain neural networks without vague phrases such as "the AI sees the image".',[("Convolution",["A convolutional filter is a small grid of learned numbers that slides across the image. At each location it multiplies nearby pixel values and adds them. The result is a feature map: locations where a pattern was detected strongly.","Early filters often respond to simple visual patterns such as edges or color transitions. Deeper filters combine earlier maps into more complex visual representations."]),("Non-linearity and depth",["Activation functions let a network model relationships more complex than one straight line. Stacking many layers lets later layers combine earlier visual evidence.","EfficientNet contains optimized convolutional building blocks. You do not need to memorize every block for a hackathon; explain the role: pixels become increasingly useful feature maps, then global average pooling turns maps into one compact embedding."]),("Global average pooling",["Instead of keeping a large spatial grid at the end, global average pooling averages each final feature map into one number. The resulting 1,280 values summarize the image efficiently.","This makes the downstream fraud head smaller and reduces overfitting risk compared with attaching a huge dense layer directly to image pixels."])],Diagram(['Pixels','Edge and texture\nfeature maps','Deep visual\nfeature maps','Global average\npooling','1,280 numbers'],'A CNN does not use one hand-written rule; it composes learned visual features across layers.'),'Explain convolution, feature map and global average pooling in everyday language.')
    section('Fine-tuning decision framework','Freezing EfficientNet is the current safe choice. Fine-tuning is a future experiment, not a compulsory upgrade.',[("When freezing is preferable",["Fraud labels are scarce, the backbone already has useful general visual knowledge, and grouped validation has not demonstrated that unfreezing improves reliable performance.","Frozen backbones train faster, are easier to reproduce and have fewer trainable parameters that can memorize small datasets."]),("When fine-tuning is worth testing",["The target images consistently differ from generic ImageNet images, a larger and cleanly grouped labelled dataset becomes available, and baseline errors show missing domain-specific visual representation.","Start by unfreezing a small final block, not the whole model. Use a very low learning rate, early stopping, saved checkpoints and separate experiment artifacts."]),("Decision record",["Record: frozen layers, trainable layers, learning rate, epoch count, early-stopping rule, augmentation policy, random seed, fold results, calibration and false-negative review.","Reject fine-tuning if it improves one metric only while worsening calibration, increasing instability, or failing on duplicate-aware validation."])])
    section('Ensemble lab manual: build confidence step by step','Role 4 should demonstrate that each ensemble component contributes useful, leakage-safe evidence.',[("Lab E - train one tree forest",["Fit a small Extra Trees forest on one fold. Compare class_weight='balanced_subsample' versus no class weighting. Observe changes in rare-class recall and false-positive count.","Then return to the project configuration: 300 trees, min_samples_leaf=2, max_features=0.20. Explain each parameter's role rather than claiming they are universally best."]),("Lab F - rotating subset audit",["Print the number of fraud and normal samples in each balanced subset. Confirm every subset contains all fraud samples and approximately eight normal samples per fraud sample.","Track normal image IDs across rotations. The goal is broad coverage across the ensemble, not permanent deletion of normal evidence."]),("Lab G - archive-similarity sanity check",["Choose a query image and calculate its closest fraud and non-fraud archive similarities. Confirm the query is never compared to itself within a validation fold.","Look at a few close matches. Explain that visual similarity is an investigation clue, not a duplicate-claim conclusion."]),("Lab H - stacking audit",["For one fold, verify the meta model sees base-model predictions created on the held-out fold. Never pass fit-fold predictions to the same fold's stacker target row.","Plot correlations between base model out-of-fold probabilities. Very high correlation suggests duplicate information; complementary models should make at least some different errors."])],Diagram(['Feature vectors','Full Extra Trees','Rotating Extra Trees','MLP','CNN score +\narchive signals','OOF stacker'],'Role 4 combines diverse evidence only after every base score is produced out of fold.'),'You can identify the exact point where stacking leakage would occur.')
    section('Probability, calibration and threshold workshop','This is the most important operational knowledge for Role 4 because a good model can cause harm if its threshold policy is misunderstood.',[("Raw score versus calibrated probability",["A base model score is a ranking signal; it may not mean that a score of 0.70 corresponds to 70% labelled-fraud frequency. Calibration learns a mapping from score to better-behaved probability.","Platt scaling fits a logistic curve using out-of-fold raw predictions and labels. It must not be trained on optimistic in-fold predictions."]),("Reliability test",["Divide predictions into score bands, for example 0.00-0.10, 0.10-0.20 and so on. In each band compare average predicted probability with observed fraud frequency.","A reliability diagram and Brier score are useful. Brier is the average squared difference between predicted probability and actual label; lower is generally better."]),("Threshold simulation",["Make a small table across several thresholds: flags per 1,000 claims, true positives, false positives, false negatives, recall, precision and estimated staff review hours.","Choose a threshold with a stated policy. The current 0.0612 review threshold is recall-first. A different insurer capacity could justify a different operating threshold without retraining the model."])],Diagram(['Base scores','Fusion raw score','Platt calibration','Probability band','Review threshold','Human queue'],'Calibration makes scores more interpretable; a threshold turns probability into a capacity-aware review action.'),'State the difference between an improved model and a changed threshold policy.')
    section('Model comparison dashboard specification','Both engineers must agree on a dashboard that prevents misleading comparisons.',[("Dashboard cards",["Show active artifact version, backbone version, feature version, evaluation date, train/test counts, fraud rate, threshold policy and leakage-audit status.","Show CNN standalone, MLP, full trees, rotating trees, archive-only baseline and full hybrid as separate rows. Do not hide weaker components."]),("Required plots",["Precision-recall curve for every candidate model, ROC curve as a secondary view, calibration/reliability curve for final candidates, confusion matrix at active threshold and flag-volume versus threshold plot.","Add a false-positive/false-negative gallery with image IDs only where privacy permits. Reviewers learn more from errors than a single metric tile."]),("Comparison rules",["Use identical data split, grouped-fold protocol and threshold-policy description. A PR AUC comparison is threshold-independent; a recall/precision comparison requires stating the threshold.","Mark all supplied-test results with the near-duplicate caveat: 53.7% perceptual overlap screen and 261 identical pHashes can make those metrics optimistic."])])
    section('Joint integration, regression testing and release','A model is not integrated until a new image can travel safely through the website and produce traceable evidence.',[("Contract between roles",["Role 3 documents preprocessing inputs, backbone filename, image size and embedding dimensions. Role 4 documents feature names, base models, stacker, calibrator and thresholds.","The application loads a matching joblib artifact and Keras backbone. Mismatched versions, changed image size or stale cache must fail explicitly instead of silently producing a score."]),("Regression test set",["Maintain a small, access-controlled set of known images: clear fraud-labelled examples, clear non-fraud examples, difficult borderline examples, corrupted upload, very small image, unusual aspect ratio and unrelated-image case.","For each release, record expected behavior: successful/failed validation, output fields present, probability within an approved tolerance and review label under the documented threshold."]),("Release gate",["No release without: reproducible training command, artifact hashes/versions, metrics report, leakage note, dashboard comparison, selected threshold rationale and website smoke test.","If any critical regression occurs, keep the previous artifact active and open an investigation rather than forcing the new model live."])],Diagram(['Train artifacts','Version checks','App load','Known-image tests','Dashboard check','Release / rollback'],'The model, website and dashboard are one release unit. A strong model file alone is not a product.'),'Describe how you would detect that the website accidentally loaded an old model.')
    section('Reviewer-ready Q&A for each role','Use these answers only after you understand the reasoning behind them.',[("Deep-Learning Engineer questions",["<b>Why EfficientNetV2B0?</b> It is a lightweight CNN that produces strong visual embeddings with manageable compute. With only 200 fraud images, transfer learning is safer than training a large CNN from scratch.","<b>What does frozen mean?</b> ImageNet backbone weights are retained; the project does not update them. Fraud-specific heads learn from supplied images on top of the frozen representation.","<b>Why not claim augmentation improved the model?</b> We only claim it after a controlled grouped-fold experiment proves improvement without unrealistic images or worse calibration."]),("Ensemble Engineer questions",["<b>Why three kinds of models?</b> CNN, MLP and Extra Trees can represent different patterns. Archive similarity adds review-oriented evidence. We verify value through ablation and out-of-fold comparison.","<b>How do you avoid stacking leakage?</b> Every training row gets base-model predictions from a fold that excluded it. Archive features for validation rows compare only against fold-fit hashes.","<b>Why is the threshold low?</b> The active threshold reflects recall-first triage: it is designed to miss fewer labelled fraud cases and therefore intentionally sends some normal cases to human review."])])
    story += [P('Final role handoff contract',h1),P('Deep-Learning Engineer hands over: reproducible preprocessing, backbone artifact, CNN scores, standalone evaluation, augmentation evidence and error analysis. Ensemble Engineer hands over: base-model ensemble, leakage-safe stacker, calibration, thresholds, comparison dashboard, capacity simulation and release note. Together, they own the integrity of the final human-review recommendation.',call),P('Do not present the roles as separate black boxes. The combined system succeeds only when preprocessing, folds, out-of-fold scores, calibration, thresholds and website integration all use the same versioned assumptions.',body)]
    doc=SimpleDocTemplate(str(OUT),pagesize=A4,rightMargin=1.7*cm,leftMargin=1.7*cm,topMargin=2.15*cm,bottomMargin=1.8*cm,title='VeriClaim Deep Learning and Ensemble Engineer Study Guide',author='VeriClaim AI Hackathon Team')
    doc.build(story,onFirstPage=header,onLaterPages=header); print(OUT)
if __name__=='__main__': build()
