"""Create and execute the AI/Analytics evidence notebook for VeriClaim."""
from pathlib import Path
import nbformat as nbf
from nbclient import NotebookClient

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "output" / "VeriClaim_AI_Analytics_Submission_Notebook.ipynb"

def md(text):
    return nbf.v4.new_markdown_cell(text)

def code(text):
    return nbf.v4.new_code_cell(text)

def main():
    nb = nbf.v4.new_notebook()
    nb.metadata.kernelspec = {"display_name": "Python 3", "language": "python", "name": "python3"}
    nb.metadata.language_info = {"name": "python", "version": "3.13"}
    cells = [
        md("# VeriClaim AI: Fraud Detection - AI & Analytics Submission\n\n**Objective:** flag potentially fraudulent vehicle-damage claims for human review. This notebook is fully executed and uses only the supplied Kaggle claim-image dataset. It documents EDA, preprocessing, feature engineering, modelling, validation, evaluation and saved-model verification."),
        md("## 1. Reproducibility and project policy\n\n- Training images: 5,200; supplied test images: 1,416.\n- Fraud is the positive class.\n- No external insurance-claim dataset, synthetic claims or SMOTE images are used.\n- Closely related photos are grouped during validation to reduce leakage.\n- The result is decision support; a human investigator owns the claim decision."),
        code("from pathlib import Path\nimport json, sys, joblib, numpy as np, pandas as pd\nimport matplotlib.pyplot as plt\nfrom PIL import Image\n\nROOT = Path.cwd()\nif not (ROOT / 'src').exists():\n    ROOT = Path(r'C:/Users/Varun/Documents/insurance-fraud-hackathon/VeriClaim_AI_Complete_Hackathon_Solution/vericlaim-ai')\nsys.path.insert(0, str(ROOT / 'src'))\nDATA = Path(r'C:/Users/Varun/Documents/insurance-fraud-hackathon/dataset1/Insurance-Fraud-Detection/Insurance-Fraud-Detection')\nMETRICS_PATH = ROOT / 'models/efficientnet_hybrid/model_metrics.json'\nMODEL_PATH = ROOT / 'models/efficientnet_hybrid/vericlaim_model.joblib'\nmetrics = json.loads(METRICS_PATH.read_text(encoding='utf-8'))\nprint('Project root:', ROOT)\nprint('Dataset root:', DATA)\nprint('Model artifact exists:', MODEL_PATH.exists())"),
        md("## 2. Dataset loading and schema\n\nThe supplied data is image-only. Its effective schema is: **file path, split, class label, image width, image height, image format**. Labels are derived from the `Fraud` and `Non-Fraud` folders."),
        code("def discover(split):\n    rows=[]\n    for label_name, label in [('Fraud',1),('Non-Fraud',0)]:\n        folder=DATA/split/label_name\n        for path in sorted(folder.rglob('*')):\n            if path.suffix.lower() in {'.jpg','.jpeg','.png','.webp'}:\n                with Image.open(path) as im:\n                    rows.append({'path':str(path),'split':split,'label':label,'class':label_name,'width':im.width,'height':im.height,'format':im.format})\n    return pd.DataFrame(rows)\ntrain_df, test_df = discover('train'), discover('test')\nall_df = pd.concat([train_df,test_df], ignore_index=True)\nprint(train_df.groupby('class').size())\nprint(test_df.groupby('class').size())\nall_df.head()"),
        md("## 3. EDA: class imbalance\n\nFraud is only 3.85% of training data (200 of 5,200). Accuracy alone would be misleading: always predicting Non-Fraud would look accurate but detect no fraud."),
        code("counts=pd.DataFrame({'Train':train_df['class'].value_counts(), 'Test':test_df['class'].value_counts()}).fillna(0)\nax=counts.loc[['Non-Fraud','Fraud']].plot(kind='bar', color=['#2D6A4F','#E76F51'], figsize=(8,4))\nax.set_title('Class counts by supplied split'); ax.set_ylabel('Images'); plt.xticks(rotation=0); plt.show()\nprint('Train fraud rate:', round(train_df.label.mean()*100,2),'%', '| Test fraud rate:',round(test_df.label.mean()*100,2),'%')"),
        md("## 4. EDA: image dimensions and file quality\n\nImage dimensions, aspect ratio and format are inspected to make preprocessing robust to heterogeneous uploads."),
        code("all_df['aspect_ratio']=all_df.width/all_df.height\nfig,axes=plt.subplots(1,2,figsize=(12,4))\nfor label,name,color in [(0,'Non-Fraud','#457B9D'),(1,'Fraud','#E76F51')]:\n    part=train_df[train_df.label==label]\n    axes[0].hist(part.width, bins=30, alpha=.6, label=name, color=color)\n    axes[1].hist(part.height, bins=30, alpha=.6, label=name, color=color)\naxes[0].set_title('Training image widths'); axes[1].set_title('Training image heights')\nfor ax in axes: ax.legend(); ax.set_xlabel('Pixels')\nplt.show()\nall_df.groupby(['split','class'])[['width','height','aspect_ratio']].median().round(2)"),
        md("## 5. Preprocessing\n\n1. Decode RGB image. 2. Resize with padding to 224 x 224 for EfficientNetV2B0. 3. Apply EfficientNet ImageNet preprocessing. 4. Extract deterministic handcrafted forensic features. 5. Keep validation/test preprocessing deterministic.\n\nTraining experiments may use small safe augmentations (horizontal flip, modest rotation, colour jitter and zoom), but no new claim data is introduced."),
        code("from vericlaim.features import extract_features, feature_names\nexample_path=Path(train_df.iloc[0].path)\nfeatures, forensic = extract_features(example_path)\nprint('Handcrafted feature dimensions:', len(features))\nprint('Example forensic fields:', forensic)\nprint('First 12 feature names:', feature_names()[:12])"),
        md("## 6. Feature engineering\n\nThe hybrid system combines two feature families:\n\n- **Visual embedding:** 1,280-dimension EfficientNetV2B0 pooled representation.\n- **Handcrafted evidence features:** colour statistics, brightness/contrast, edge density/orientation, image dimensions, quality and perceptual hashes.\n\nThe image-only dataset has no trustworthy claim amount, policy or customer metadata, so none is invented for model training."),
        code("summary = pd.DataFrame([{'feature_family':'EfficientNetV2B0 embedding','dimensions':metrics['cnn']['embedding_dimensions'],'purpose':'learned visual representation'}, {'feature_family':'Handcrafted image/forensic features','dimensions':len(features),'purpose':'deterministic evidence signals'}, {'feature_family':'Archive similarity','dimensions':2,'purpose':'fraud and non-fraud reference similarity'}])\nsummary"),
        md("## 7. Leakage-aware validation\n\nA standard random split can place near-duplicate photographs in both train and validation folds. VeriClaim clusters close perceptual hashes and uses **5-fold StratifiedGroupKFold** so related image groups stay together. The supplied test split was not used for threshold selection, but its perceptual overlap is disclosed as a limitation."),
        code("audit=metrics['leakage_audit']['perceptual_screen']\nprint('Grouped training clusters:',metrics['validation_protocol']['train_perceptual_groups'])\nprint('Exact train-test file duplicates:',metrics['leakage_audit']['exact_train_test_duplicates'])\nprint('Test images with close perceptual train match:',audit['test_images_with_close_train_match'],'/',metrics['dataset']['test_images'])\npd.Series(audit['nearest_distance_histogram']).sort_index().rename('test images').to_frame()"),
        md("## 8. Imbalance strategy\n\nWe retain all 5,200 training images. Fraud examples are made more influential through class-weighted learning and rotating balanced subsets. Each rotating Extra Trees model sees every fraud image and a different approximately 1:8 sample of Non-Fraud images. This avoids discarding normal images permanently and avoids fabricating synthetic images."),
        code("imb=metrics['imbalance_strategy']\npd.DataFrame({'policy':['External data','All training images retained','CNN class weighting','MLP fraud weighting','Rotating balanced models','Non-Fraud per Fraud'], 'value':[imb['external_claim_data'],imb['kept_all_training_images'],imb['cnn_head_class_weight'],imb['mlp_fraud_weighted'],imb['rotating_balanced_models'],imb['nonfraud_per_fraud']]})"),
        md("## 9. Neural model: EfficientNetV2B0\n\nEfficientNetV2B0 is the primary CNN. It receives a 224 x 224 image and produces a 1,280-value representation. Five fraud-weighted sigmoid heads are trained in grouped folds. The pretrained ImageNet backbone supplies generic edge/shape/texture knowledge; only the classifier heads learn from the supplied vehicle-claim images."),
        code("pd.DataFrame([metrics['cnn']])"),
        md("## 10. Non-neural models\n\n- **Full-data Extra Trees:** robust non-linear rules across all handcrafted features.\n- **Rotating balanced Extra Trees:** counter minority-class neglect by repeatedly changing the non-fraud subset.\n- **MLP:** a small dense neural classifier over engineered features.\n- **Archive similarity:** compares perceptual fingerprints with known Fraud and Non-Fraud training references.\n\nThese are complementary opinions; none alone is the final decision."),
        code("from vericlaim.model import VeriClaimModel\nmodel=VeriClaimModel.load(MODEL_PATH)\nprint('Full-data Extra Trees models:',len(model.full_models))\nprint('Rotating balanced Extra Trees models:',len(model.balanced_models))\nprint('MLP models:',len(model.neural_models))\nprint('EfficientNet heads:',len(model.cnn_models))\nprint('Thresholds:',model.thresholds)"),
        md("## 11. Hybrid fusion and calibration\n\nOut-of-fold predictions from Extra Trees, rotating Extra Trees, MLP, EfficientNet and archive similarity become inputs to a class-weighted logistic stacker. **Platt scaling** then calibrates the final score so a probability better reflects the rare-fraud setting. Thresholds are selected on out-of-fold training predictions, never by searching the supplied test labels."),
        code("pd.DataFrame({'stage':['Signals','Meta model','Calibration','Validation'], 'implementation':[', '.join(metrics['fusion']['signals']),metrics['fusion']['meta_model'],metrics['fusion']['probability_calibration'],metrics['validation_protocol']['method']]})"),
        md("## 12. Training configuration and tuning\n\nMain final configuration: 5 grouped folds, 224-pixel CNN input, 300 trees per full-data Extra Trees model, 100 trees per rotating model, 1:8 fraud/non-fraud ratio, and a recall target of 0.99 for broad screening. The selected deployed binary threshold maximizes precision while retaining at least 75% recall in grouped out-of-fold predictions."),
        code("config=pd.DataFrame({'hyperparameter':['Fold count','CNN image size','Full-data Extra Trees','Balanced Extra Trees per fold','Rotating ratio','Recall target','Balanced binary threshold','High-confidence threshold'], 'value':[5,224,300,100,'1 : 8',metrics['validation_protocol']['recall_target'],metrics['default_thresholds']['classification'],metrics['default_thresholds']['investigate']]})\nconfig"),
        md("## 13. Evaluation metrics\n\nFor rare fraud, report precision, fraud recall, F1/F2, PR-AUC, ROC-AUC, Brier score and the confusion matrix. Accuracy is included, but is not the leading measure."),
        code("balanced=metrics['classification_metrics']; broad=metrics['test_metrics']; cnn=metrics['cnn_standalone_metrics']\ncomparison=pd.DataFrame([cnn,balanced,broad],index=['EfficientNet CNN standalone','Hybrid - balanced binary','Hybrid - broad screening'])[['accuracy','balanced_accuracy','precision','recall','f1','f2','roc_auc','pr_auc','brier','threshold']]\ncomparison.round(4)"),
        code("plot_cols=['precision','recall','f1','pr_auc']\ncomparison[plot_cols].T.plot(kind='bar', figsize=(10,5), color=['#6C8EBF','#2D6A4F','#E76F51'])\nplt.ylim(0,1); plt.title('Performance comparison by operating mode'); plt.ylabel('Score'); plt.xticks(rotation=0); plt.legend(loc='lower right'); plt.show()"),
        md("## 14. Confusion matrices\n\nThe balanced binary threshold is the website's `FRAUD / NOT FRAUD` screen. Broad screening intentionally accepts many more manual reviews to minimize missed fraud. High-confidence alerts are a stricter prioritization band, not a denial rule."),
        code("fig,axes=plt.subplots(1,2,figsize=(10,4))\nfor ax,(name,row) in zip(axes,[('Balanced binary',balanced),('Broad screening',broad)]):\n    cm=row['confusion_matrix']; matrix=np.array([[cm['tn'],cm['fp']],[cm['fn'],cm['tp']]])\n    im=ax.imshow(matrix,cmap='YlGn'); ax.set_title(name); ax.set_xticks([0,1],['Pred. non-fraud','Pred. fraud']); ax.set_yticks([0,1],['Actual non-fraud','Actual fraud'])\n    for i in range(2):\n        for j in range(2): ax.text(j,i,str(matrix[i,j]),ha='center',va='center',fontsize=15)\nplt.tight_layout(); plt.show()"),
        md("## 15. Results and interpretation\n\nAt the balanced binary threshold, the deployed hybrid achieves 96.12% accuracy, 94.42% balanced accuracy, 64.18% precision, 92.47% fraud recall, 75.77% F1 and 90.48% PR-AUC on the supplied test split. It detects 86 of 93 Fraud images, misses 7, and flags 48 Non-Fraud images for review.\n\nThe strict high-confidence band improves operational precision by escalating only the strongest scores, but reduces recall; it is therefore used for prioritization, not final claim disposition."),
        code("pd.DataFrame([balanced['confusion_matrix']]).assign(**{k:balanced[k] for k in ['accuracy','precision','recall','f1','pr_auc','brier']}).T.rename(columns={0:'Balanced hybrid test result'})"),
        md("## 16. Explainability, Evidence DNA and governance\n\nGrad-CAM is generated for the CNN component to show regions that influenced its visual score. Transformation-Resistant Evidence DNA separately compares SHA-256, perceptual/difference hashes, overlapping patches, colour and edge descriptors to flag possible reuse after crop, flip, inversion, rotation, resize or compression. Neither Grad-CAM nor an Evidence DNA match proves fraud; both route the case to human verification."),
        code("from vericlaim.evidence_matching import build_evidence_dna\nraw=example_path.read_bytes()\ndna=build_evidence_dna(raw)\nprint('Evidence DNA fields:',sorted(dna.keys()))\nprint('Saved model loaded successfully:', type(model).__name__)\nprint('Saved artifact family:',model.artifact['model_family'])"),
        md("## 17. Reproducibility checklist\n\n- Notebook outputs are visible.\n- Dataset location is parameterized at the top.\n- Final model artifact is loaded from `models/efficientnet_hybrid/vericlaim_model.joblib`.\n- Metrics come from the matching `model_metrics.json`.\n- Full training implementation is available in `src/vericlaim/train_efficientnet_hybrid.py`.\n- Limitations: supplied test split contains perceptual overlap with training; external claim validation is required before production use."),
        code("print('Notebook complete.')\nprint('PKL/JOBLIB artifact:', MODEL_PATH)\nprint('Metrics report:', METRICS_PATH)\nprint('Training source:', ROOT/'src/vericlaim/train_efficientnet_hybrid.py')")
    ]
    nb['cells'] = cells
    OUT.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(nb, OUT)
    client = NotebookClient(nb, timeout=600, kernel_name='python3', resources={'metadata': {'path': str(ROOT)}})
    client.execute(cwd=str(ROOT))
    nbf.write(nb, OUT)
    print(OUT)

if __name__ == '__main__':
    main()
