from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, Flowable

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "output" / "pdf" / "VeriClaim_AI_Beginner_to_Expert_Guide.pdf"
NAVY, TEAL, MINT, PALE, INK, MUTED, RED = (colors.HexColor(x) for x in ("#102A43", "#087E8B", "#DFF4F0", "#F5F8FA", "#172B4D", "#52616B", "#C94C4C"))

class FlowDiagram(Flowable):
    def __init__(self, labels, note):
        super().__init__(); self.labels, self.note = labels, note; self.width, self.height = 17*cm, 4.2*cm
    def draw(self):
        c=self.canv; c.setFillColor(PALE); c.roundRect(0,0,self.width,self.height,10,fill=1,stroke=0)
        n=len(self.labels); w=3.35*cm; gap=(self.width-n*w)/(n+1)
        for i,label in enumerate(self.labels):
            x=gap+i*(w+gap); c.setFillColor(MINT); c.setStrokeColor(TEAL); c.roundRect(x,1.75*cm,w,1.1*cm,7,fill=1,stroke=1)
            c.setFillColor(NAVY); c.setFont("Helvetica-Bold",7.5)
            for j,line in enumerate(label.split("\n")): c.drawCentredString(x+w/2,2.4*cm-j*.27*cm,line)
            if i<n-1:
                c.setStrokeColor(TEAL); c.line(x+w,2.3*cm,x+w+gap,2.3*cm); c.setFillColor(TEAL); c.circle(x+w+gap,2.3*cm,2,fill=1,stroke=0)
        c.setFillColor(MUTED); c.setFont("Helvetica-Oblique",7); c.drawCentredString(self.width/2,.55*cm,self.note)

def header(canvas, doc):
    canvas.saveState()
    if doc.page > 1:
        canvas.setStrokeColor(colors.HexColor("#D7E2E8")); canvas.line(1.7*cm,28.2*cm,19.3*cm,28.2*cm); canvas.line(1.7*cm,1.45*cm,19.3*cm,1.45*cm)
        canvas.setFillColor(MUTED); canvas.setFont("Helvetica",8); canvas.drawString(1.7*cm,28.45*cm,"VERICLAIM AI - BEGINNER TO EXPERT GUIDE"); canvas.drawRightString(19.3*cm,1.15*cm,f"Page {doc.page}")
    canvas.restoreState()

def make_table(rows, widths, text_style):
    t=Table([[Paragraph(str(x),text_style) for x in r] for r in rows],colWidths=widths,repeatRows=1)
    t.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),NAVY),("TEXTCOLOR",(0,0),(-1,0),colors.white),("BACKGROUND",(0,1),(-1,-1),PALE),("GRID",(0,0),(-1,-1),.35,colors.HexColor("#C7D5DB")),("VALIGN",(0,0),(-1,-1),"TOP"),("TOPPADDING",(0,0),(-1,-1),6),("BOTTOMPADDING",(0,0),(-1,-1),6)]))
    return t

def build():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    ss=getSampleStyleSheet()
    title=ParagraphStyle("title",parent=ss["Title"],fontName="Helvetica-Bold",fontSize=28,leading=34,textColor=NAVY,alignment=TA_CENTER,spaceAfter=10)
    sub=ParagraphStyle("sub",parent=ss["Normal"],fontName="Helvetica",fontSize=12,leading=18,textColor=MUTED,alignment=TA_CENTER)
    h1=ParagraphStyle("h1",parent=ss["Heading1"],fontName="Helvetica-Bold",fontSize=20,leading=25,textColor=NAVY,spaceAfter=10)
    h2=ParagraphStyle("h2",parent=ss["Heading2"],fontName="Helvetica-Bold",fontSize=13,leading=17,textColor=TEAL,spaceBefore=10,spaceAfter=5)
    body=ParagraphStyle("body",parent=ss["BodyText"],fontName="Helvetica",fontSize=9.2,leading=13.4,textColor=INK,spaceAfter=6)
    small=ParagraphStyle("small",parent=body,fontSize=8,leading=11,textColor=MUTED)
    call=ParagraphStyle("call",parent=body,backColor=MINT,borderColor=TEAL,borderWidth=.7,borderPadding=9,spaceBefore=4,spaceAfter=10)
    bullet=ParagraphStyle("bullet",parent=body,leftIndent=14,firstLineIndent=-10,bulletIndent=2,spaceAfter=3)
    P=lambda x,s=body,**kw: Paragraph(x,s,**kw)
    B=lambda x: P(x,bullet,bulletText="-")
    story=[]
    story += [Spacer(1,3.7*cm),P("VERICLAIM AI",ParagraphStyle("k",parent=sub,fontName="Helvetica-Bold",textColor=TEAL,fontSize=12)),Spacer(1,.2*cm),P("Beginner to Expert Guide",title),P("Learn the complete fraud-triage project from first principles and explain it confidently to a reviewer or judge.",sub),Spacer(1,.8*cm)]
    cover=Table([[P("<b>Who this is for</b><br/>A developer with minimal AI, machine-learning or insurance-domain knowledge.",body),P("<b>What you will gain</b><br/>The ability to explain the project, operate the demo, read the code, discuss results and propose responsible improvements.",body)]],colWidths=[8.2*cm,8.2*cm])
    cover.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),MINT),("BOX",(0,0),(-1,-1),.8,TEAL),("INNERGRID",(0,0),(-1,-1),.3,TEAL),("VALIGN",(0,0),(-1,-1),"TOP"),("TOPPADDING",(0,0),(-1,-1),12),("BOTTOMPADDING",(0,0),(-1,-1),12),("LEFTPADDING",(0,0),(-1,-1),12)]))
    story += [cover,Spacer(1,.7*cm),P("Core message: VeriClaim AI is not a system that decides a customer committed fraud. It is a human-led tool that uses image evidence to decide which claims deserve earlier investigation.",call),PageBreak()]
    story += [P("How to use this book",h1),P("Read it in order once. Then use the sections as a speaking guide before your demo. Every chapter has two levels: a simple explanation you can say to a judge and the technical detail you need when they ask follow-up questions.",body),P("Learning route",h2)]
    for x in ["Start with Chapters 1-5 for the story of the solution.","Study Chapters 6-10 to understand exactly how the trained model operates.","Use Chapters 11-14 to explain results, risks, the website and future work.","Practise Chapter 15 aloud. It contains direct answers to likely judge questions."] : story.append(B(x))
    story += [P("Contents",h2)]
    for x in ["1. Problem statement and business context","2. Essential AI vocabulary","3. Dataset and label schema","4. Supervised learning from scratch","5. Why class imbalance matters","6. Our balancing strategy","7. What a neural network is","8. EfficientNetV2B0 explained","9. The complete hybrid ensemble","10. From upload to result","11. Metrics, threshold and comparison","12. Leakage, fairness and limitations","13. Website and standout contributions","14. How to run, test and improve","15. Judge-ready explanation and Q&A","16. Glossary and 30-day study plan"]: story.append(B(x))
    story.append(PageBreak())

    def chapter(number,title_,intro,sections,diagram=None):
        story.append(P(f"{number}. {title_}",h1)); story.append(P(intro,body))
        if diagram: story.extend([diagram,Spacer(1,.25*cm)])
        for heading,paragraphs in sections:
            story.append(P(heading,h2))
            for p in paragraphs:
                story.append(B(p[2:]) if p.startswith("- ") else P(p,body))
        story.append(PageBreak())

    chapter(1,"Problem statement and business context","The objective is to flag potentially fraudulent vehicle-damage claims for review. The word 'potentially' is crucial: the output is a priority signal, not a fraud verdict.",[("Why insurers need triage",["Claims teams may receive many images but only a small fraction have fraud labels. Sending every claim through an intensive manual investigation is slow and expensive. A triage system helps investigators spend time where evidence is more unusual or more similar to prior labelled cases.","The project is valuable when it improves review order, preserves evidence and gives a reviewer enough context to make an informed human decision."]),("The correct problem framing",["The technical task is binary image classification: learn a mapping from an image to one of two supplied labels, fraud or non-fraud.","The real business task is risk ranking: place likely suspicious claims nearer the top of a review queue.","- Never claim that the system proves intent, crime or customer dishonesty.","- Never use a single image score as an automatic rejection."])],FlowDiagram(["Claim image","AI evidence\nassessment","Risk score","Human review"],"The model assists an investigator; the investigator makes the insurance decision."))
    chapter(2,"Essential AI vocabulary","You do not need to memorize mathematics before understanding this project. Learn the following meanings first.",[("AI, machine learning and deep learning",["Artificial intelligence is the broad idea of computers doing tasks associated with human intelligence. Machine learning is a practical part of AI where a system learns patterns from examples. Deep learning is machine learning using neural networks with many connected layers.","This project uses both classical machine learning and deep learning. EfficientNetV2B0 and MLPs are neural networks. Extra Trees and logistic regression are classical ML models."]),("Training, validation and testing",["Training is when models learn from labelled examples. Validation helps choose settings such as threshold without repeatedly touching final evaluation data. Testing estimates how the finished model performs on unseen labelled images.","A model may look very accurate during training but fail on unfamiliar photos. That is called overfitting."]),("Feature and prediction",["A feature is a useful numeric clue. Pixel values are basic features; a CNN creates richer visual features such as a 1,280-number embedding. A prediction is the score produced from those features."])])
    chapter(3,"Dataset and label schema","The project is trained only on the supplied hackathon image dataset. No additional insurance dataset or synthetic claim data was added.",[("Dataset counts",["Training split: 5,200 images, made of 200 fraud and 5,000 non-fraud examples.","Supplied test split: 1,416 images, made of 93 fraud and 1,323 non-fraud examples.","The label schema is binary. Each image has one target value: fraud = 1 or non-fraud = 0. Optional damage categories are not required because the supplied test data does not consistently provide them."]),("What the label means",["The label is an answer included by the dataset creator. The model learns visual correlations with that label. It does not independently verify why that historical label was assigned.","Label quality determines the ceiling of model quality. If labels are noisy, biased or incomplete, the model can inherit those problems."])])
    story.append(make_table([["Split","Images","Fraud","Non-fraud","Fraud rate"],["Training","5,200","200","5,000","3.85%"],["Supplied test","1,416","93","1,323","6.57%"]],[3.2*cm,2.4*cm,2.4*cm,3.1*cm,2.5*cm],small)); story.append(PageBreak())
    chapter(4,"Supervised learning from scratch","VeriClaim uses supervised learning because each training image comes with a known answer.",[("Flashcard analogy",["Think of the dataset as 5,200 flashcards. The front has a vehicle-damage photo; the back has 'fraud' or 'non-fraud'. The system sees many flashcards, makes a guess, compares it with the answer and adjusts itself to make fewer mistakes next time.","At the end, it is shown a new image without the answer. It uses patterns learned from the old flashcards to estimate a probability."]),("The training loop",["1. Read and resize an image.","2. Convert pixels into useful numerical features.","3. Make a fraud-probability prediction.","4. Compare prediction with the known label using a loss function.","5. Change model parameters slightly to reduce loss.","6. Repeat across many examples and epochs."]),("Important limitation",["The system learns association, not causation. It can learn that certain visual characteristics were common among images labelled fraud; it does not know a customer's true intent."])],FlowDiagram(["Labelled image","Model guesses","Compare label","Adjust model"],"Training repeats many times. Prediction uses the frozen trained model."))
    chapter(5,"Why class imbalance matters","Fraud labels are rare: only 200 of 5,200 training photos, or roughly one in twenty-six. This is called class imbalance.",[("The misleading easy answer",["If a naive model says 'non-fraud' for every photo, it would appear about 96% accurate on the training distribution. Yet it would detect zero fraud cases. This is why accuracy alone is not enough."]),("What we optimize",["Recall asks: of all actual labelled fraud cases, how many did we flag? High recall reduces missed suspicious cases.","Precision asks: of cases we flagged, how many were actually labelled fraud? Higher precision reduces unnecessary review work.","The project uses a recall-aware threshold because missing a labelled fraud case is costly for triage. The trade-off is some normal claims will be reviewed."])])
    chapter(6,"Our balancing strategy","We do not create extra claim images and we do not permanently throw away most normal photos. We use cost-sensitive learning and a rotating balanced ensemble.",[("Method 1: class weighting",["During MLP training, an error on a fraud image receives about 25 times the importance of an error on a normal image. In simple words: the model is told, 'a missed rare fraud example matters much more during learning'.","This is called class weighting or cost-sensitive learning. It changes the penalty in training; it does not duplicate the image file."]),("Method 2: rotating balanced Extra Trees",["Each of 20 rotating tree learners sees every fraud photo and a different 1:8 fraud-to-normal subset. One learner sees fraud plus normal group A; the next sees fraud plus group B. Their scores are averaged.","This lets the model learn from all normal examples across the ensemble while avoiding a single learner being overwhelmed by normal examples."]),("Why we do not train and test with equal counts",["Making test data 50:50 would make evaluation unrealistic. Real review queues are imbalanced, so final test metrics should preserve the provided distribution. Balanced training and realistic evaluation solve different problems."])],FlowDiagram(["Every fraud\nphoto","Normal group A","Normal group B","20 tree votes"],"Fraud receives emphasis; normal examples rotate through learners rather than being discarded."))
    chapter(7,"What a neural network is","A neural network is a flexible mathematical function with adjustable connections. It learns which combinations of inputs help predict the supplied labels.",[("Neuron intuition",["A basic artificial neuron receives numbers, multiplies them by adjustable weights, combines them, and passes the result through an activation function. Many neurons together can represent complicated relationships.","The weights begin mostly random. Training gradually changes them so useful visual patterns contribute more strongly to the final score."]),("CNN versus MLP",["A convolutional neural network, or CNN, is specialized for images. It reads nearby pixels together and can recognize edges, textures and shapes regardless of their exact location.","A multilayer perceptron, or MLP, is a general neural network. In this project it reads the CNN's compact numeric image summary rather than raw image pixels."]),("Why neural networks are not simple rules",["There is no line of code saying 'tire equals fraud'. The learned decision is spread across many numeric weights and features. This explains why two visually similar tire photos can receive different scores."])])
    chapter(8,"EfficientNetV2B0 explained","EfficientNetV2B0 is the project's image-analysis backbone. It is a lightweight CNN chosen because it offers strong image features without the heavy computing cost of very large vision models.",[("What it receives and produces",["The uploaded photo is resized to 224 x 224 pixels. EfficientNet processes it through many convolutional layers and outputs a 1,280-number visual embedding.","An embedding is like a compact fingerprint of the image's visual patterns. It is not a written description, but downstream models can use it to distinguish examples."]),("Pretraining",["EfficientNet begins with ImageNet-pretrained visual knowledge. This means it already recognizes general image structures such as edges, textures and objects. It was not trained with an external insurance dataset for this project.","Transfer learning reuses general visual knowledge, then our fraud models learn from the supplied claim images."]),("Why use this model",["It is more capable than raw pixels or a very small custom CNN when data is limited. It is lighter and easier to deploy than many larger alternatives, making it suitable for a hackathon application."])])
    chapter(9,"The complete hybrid ensemble","The deployed system combines several models because each sees a different type of evidence. This is an ensemble, meaning multiple estimators vote or contribute to one final answer.",[("Component 1: MLP ensemble",["Five MLP neural networks score the EfficientNet embedding. Using several models and averaging them reduces dependence on a single random training outcome."]),("Component 2: Extra Trees",["Extra Trees are many randomized decision trees. A tree asks feature questions and reaches a score; a forest averages many trees. The project includes full-data and rotating balanced tree learners."]),("Component 3: fraud archive similarity",["Perceptual hashing, or pHash, makes a short visual signature. The system compares the uploaded photo with the archived fraud images to find close visual matches. This is an evidence signal, not a conviction."]),("Component 4: fusion and calibration",["A logistic-regression fusion model combines CNN/MLP score, tree score and archive evidence. Platt calibration then adjusts the raw score to make the displayed probability more interpretable."])],FlowDiagram(["EfficientNet\nembedding","MLP score","Tree score","Archive match","Calibrated result"],"No single component is presented as the complete truth; evidence is fused before human triage."))
    chapter(10,"From upload to result","The Model Lab uses the saved trained artifacts to analyze an uploaded image. The prediction path must match the training preprocessing exactly.",[("Step-by-step prediction path",["1. User uploads a vehicle-damage image. Optional damage context may be supplied but is not required.","2. The app validates the file and creates the 224 x 224 image representation.","3. EfficientNet creates the 1,280-number embedding.","4. MLP and Extra Trees ensembles score the embedding; pHash checks archive similarity.","5. Fusion and calibration produce one fraud-risk probability.","6. The application compares probability with the operating threshold of 0.0612.","7. At or above threshold it displays 'Fraud - review recommended'; otherwise 'Non-fraud - no fraud flag'."]),("Why the threshold looks low",["A threshold is not a probability of guilt. It is an operating rule chosen to catch more labelled fraud cases. Lowering it raises recall but increases false positives. Raising it reduces review workload but misses more fraud."])])
    chapter(11,"Metrics, threshold and model comparison","A good model report tells the whole story, including mistakes. The numbers below are from the supplied test split and should be described as hackathon evaluation results, not a production guarantee.",[("Current EfficientNet hybrid results",["Accuracy: 96.12%. Balanced accuracy: 94.42%. Fraud recall: 92.47%. Precision: 64.18%. F1: 75.77%. F2: 84.98%. ROC AUC: 0.9759. PR AUC: 0.9048.","Confusion matrix: 1,275 true negatives, 48 false positives, 7 false negatives and 86 true positives."]),("Comparison with previous MLP hybrid",["The previous hybrid achieved 83.33% accuracy, 81.72% recall, 25.76% precision and 0.6438 PR AUC. The EfficientNet hybrid improves both recall and precision on the supplied split."]),("Explain this to a judge",["Say: 'The current model flagged 86 of 93 labelled fraud test images and missed 7. It also flagged 48 normal images for review. We selected this trade-off deliberately because the system prioritizes detection for human review, not automatic denial.'"])])
    chapter(12,"Leakage, fairness and limitations","Expert-level project knowledge includes knowing where a result may be too optimistic and how to communicate that honestly.",[("Leakage risk",["A perceptual audit found 53.7% of supplied test images were close visual matches to training images, including 261 identical perceptual hashes. This may make test performance look better than it would on completely new vehicles and scenes.","The correct improvement is duplicate-aware grouped splitting: near-duplicate photo clusters must stay together in training or testing, never both."]),("Other limitations",["The model has no current damage-localization box and no Grad-CAM heatmap showing where it looked.","It is limited to the supplied data distribution. Unrelated images, unusual lighting, different countries or new camera styles can lead to unreliable predictions.","Data labels may include mistakes. The model can learn dataset bias rather than a universal fraud signal."]),("Responsible use",["- Keep a human investigator in charge.","- Preserve an audit trail: score, threshold, model version and evidence.","- Monitor false positives, false negatives and performance drift.","- Explain uncertainty and allow a reviewer to override the system."])])
    chapter(13,"Website and standout contributions","The website turns a model into a usable hackathon product. It demonstrates how different people would interact with the system, not just how a notebook prints a prediction.",[("Customer-facing ideas",["A clear homepage, claim initiation, policy and claim tracking, evidence upload, FAQs and support help make the concept understandable for customers."]),("Staff and investigator value",["The staff portal concept shows pending claims, fraud alerts, communication records, verification workflow, governance and analytics. The Model Lab lets a presenter upload an image and see the model in action."]),("Unique contributions",["Claim DNA Passport: a review-ready record of image, score, threshold, model version and evidence summary.","Twin Radar: archive similarity signal that helps an investigator discover visually close labelled fraud evidence.","Human-led governance: clear language that an AI score is a triage recommendation, not a verdict.","Model comparison: previous and current models can be tested side-by-side, making progress visible rather than merely claimed."])])
    chapter(14,"How to run, test and improve","A knowledgeable developer can reproduce a result, test its behavior and know what changes are safe.",[("Key files",["src/vericlaim/train_efficientnet_hybrid.py trains embeddings, MLPs, Extra Trees, archive similarity, fusion and calibration.","src/vericlaim/app.py connects the model to the website.","models/efficientnet_hybrid/vericlaim_model.joblib stores the hybrid artifact.","models/efficientnet_hybrid/efficientnetv2b0_backbone.keras stores the CNN backbone.","docs/model_card.md and docs/architecture.md document use, metrics and system design."]),("Safe experiment procedure",["1. Record the current artifact version and metrics before any change.","2. Change one thing at a time: threshold, weighting, augmentation or architecture.","3. Train only on the training partition; never tune repeatedly against the final test split.","4. Evaluate accuracy, recall, precision, F1, F2, PR AUC and calibration together.","5. Test Model Lab with known examples and record unexpected behavior.","6. Keep a changelog so judges can see evidence-based iteration."]),("Good future improvements",["Grad-CAM for visual explanation, out-of-distribution warnings, duplicate-aware splits, carefully controlled augmentation, damage localization when box labels exist, and monitoring after deployment."])])
    chapter(15,"Judge-ready explanation and Q&A","Use these answers as a starting point. Speak in your own words and always state both the benefit and the limitation.",[("One-minute pitch",["'VeriClaim AI is a human-led fraud-triage platform for vehicle-damage claims. A claimant or investigator uploads a photo. EfficientNetV2B0 extracts visual features, neural and tree ensembles estimate risk, and a fraud archive checks close visual similarity. A calibrated fusion model prioritizes suspicious cases for staff review. We handle severe class imbalance through fraud-weighted learning and rotating 1:8 balanced tree ensembles, without adding an external insurance dataset. The system achieves 92.47% recall and 64.18% precision on the supplied test split, but we explicitly disclose near-duplicate leakage risk and keep humans in control.'"]),("Likely questions",["<b>Why not use only a CNN?</b> The CNN creates strong visual features, but MLPs, trees and archive similarity provide diverse evidence. Fusion can be more robust than one estimator alone.","<b>Why does one tire image score fraud and another non-fraud?</b> The model learned complete visual correlations from the dataset, not a single tire rule. Background, crop, texture, damage pattern and archive similarity affect the embedding and score.","<b>How did you solve imbalance?</b> We used class weighting of about 25:1 for fraud in neural components plus rotating 1:8 fraud-to-normal Extra Trees learners. We preserved realistic imbalance in evaluation.","<b>Is 96.12% accuracy enough?</b> No. Accuracy is misleading with rare fraud. We also report recall, precision, F-scores, PR AUC and the confusion matrix.","<b>What is your biggest limitation?</b> Near-duplicate images across supplied train and test data may inflate performance. The next evaluation must use duplicate-aware grouped splits.","<b>Does the model reject claims automatically?</b> No. It is a review-prioritization system with an investigator decision at the end."])])
    chapter(16,"Glossary and 30-day study plan","Expertise comes from repeated explanation and testing, not one reading. Use this plan to become confident.",[("Key terms",["Embedding: numeric summary of an image. Calibration: making a score easier to interpret as probability. Threshold: boundary for a review flag. Ensemble: multiple models combined. Recall: fraction of labelled fraud found. Precision: fraction of flags that were labelled fraud. Leakage: accidental information that makes evaluation too easy."]),("Thirty-day plan",["Days 1-3: reread Chapters 1-6 and explain class imbalance to a friend without notes.","Days 4-7: learn CNN, embedding, MLP, Extra Trees and logistic regression concepts from Chapters 7-9.","Days 8-12: inspect the training script and draw the architecture yourself.","Days 13-17: run the website, upload known images and write observations.","Days 18-22: practise metrics and confusion-matrix explanations aloud.","Days 23-26: prepare answers on leakage, fairness and limitations.","Days 27-30: deliver the one-minute pitch and a five-minute demo repeatedly until it feels natural."])])
    story.append(P("Final reminder",h1)); story.append(P("A reviewer is usually more impressed by a team that understands its model's limitations, explains its choices clearly and proposes a credible next step than by a team that only repeats a high accuracy number.",call)); story.append(P("You are ready when you can explain: what the model learns, why fraud needs extra attention, how the ensemble makes a decision, what the metrics mean, and why a human remains responsible.",body))
    doc=SimpleDocTemplate(str(OUT),pagesize=A4,rightMargin=1.7*cm,leftMargin=1.7*cm,topMargin=2.15*cm,bottomMargin=1.8*cm,title="VeriClaim AI Beginner to Expert Guide",author="VeriClaim AI Hackathon Team")
    doc.build(story,onFirstPage=header,onLaterPages=header)
    print(OUT)

if __name__ == '__main__': build()
