from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, Flowable, KeepTogether

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "output" / "pdf" / "VeriClaim_AI_From_Zero_to_Judge_Ready_Masterclass.pdf"
NAVY, TEAL, MINT, PALE, INK, MUTED, AMBER, RED = [colors.HexColor(x) for x in ("#102A43", "#087E8B", "#DFF4F0", "#F5F8FA", "#172B4D", "#52616B", "#FFF1CC", "#C94C4C")]

class Pipeline(Flowable):
    def __init__(self, boxes, caption):
        super().__init__(); self.boxes=boxes; self.caption=caption; self.width=17*cm; self.height=4.2*cm
    def draw(self):
        c=self.canv; c.setFillColor(PALE); c.roundRect(0,0,self.width,self.height,12,fill=1,stroke=0)
        n=len(self.boxes); w=3.0*cm; gap=(self.width-n*w)/(n+1)
        for i,b in enumerate(self.boxes):
            x=gap+i*(w+gap); c.setFillColor(MINT); c.setStrokeColor(TEAL); c.roundRect(x,1.7*cm,w,1.15*cm,7,fill=1,stroke=1)
            c.setFillColor(NAVY); c.setFont("Helvetica-Bold",7)
            for j,line in enumerate(b.split("\n")): c.drawCentredString(x+w/2,2.35*cm-j*.27*cm,line)
            if i<n-1:
                c.setStrokeColor(TEAL); c.setLineWidth(1.1); c.line(x+w,2.27*cm,x+w+gap,2.27*cm); c.setFillColor(TEAL); c.circle(x+w+gap,2.27*cm,2,fill=1,stroke=0)
        c.setFillColor(MUTED); c.setFont("Helvetica-Oblique",7); c.drawCentredString(self.width/2,.55*cm,self.caption)

def header(canvas, doc):
    canvas.saveState()
    if doc.page > 1:
        canvas.setStrokeColor(colors.HexColor("#D7E2E8")); canvas.line(1.7*cm,28.2*cm,19.3*cm,28.2*cm); canvas.line(1.7*cm,1.45*cm,19.3*cm,1.45*cm)
        canvas.setFillColor(MUTED); canvas.setFont("Helvetica",8); canvas.drawString(1.7*cm,28.45*cm,"VERICLAIM AI MASTERCLASS - FROM ZERO TO JUDGE READY"); canvas.drawRightString(19.3*cm,1.15*cm,f"Page {doc.page}")
    canvas.restoreState()

def build():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    ss=getSampleStyleSheet()
    title=ParagraphStyle("title",parent=ss["Title"],fontName="Helvetica-Bold",fontSize=29,leading=35,textColor=NAVY,alignment=TA_CENTER)
    sub=ParagraphStyle("sub",parent=ss["Normal"],fontName="Helvetica",fontSize=12,leading=18,textColor=MUTED,alignment=TA_CENTER)
    h1=ParagraphStyle("h1",parent=ss["Heading1"],fontName="Helvetica-Bold",fontSize=19,leading=24,textColor=NAVY,spaceAfter=9)
    h2=ParagraphStyle("h2",parent=ss["Heading2"],fontName="Helvetica-Bold",fontSize=12.4,leading=16,textColor=TEAL,spaceBefore=10,spaceAfter=5)
    body=ParagraphStyle("body",parent=ss["BodyText"],fontName="Helvetica",fontSize=9.1,leading=13.2,textColor=INK,spaceAfter=6)
    bullet=ParagraphStyle("bullet",parent=body,leftIndent=15,firstLineIndent=-10,bulletIndent=2,spaceAfter=3)
    small=ParagraphStyle("small",parent=body,fontSize=7.8,leading=10,textColor=MUTED)
    call=ParagraphStyle("call",parent=body,backColor=MINT,borderColor=TEAL,borderWidth=.7,borderPadding=9,spaceBefore=5,spaceAfter=9)
    warning=ParagraphStyle("warn",parent=body,backColor=AMBER,borderColor=colors.HexColor("#D99A00"),borderWidth=.7,borderPadding=9,spaceBefore=5,spaceAfter=9)
    P=lambda x,s=body,**kwargs: Paragraph(x,s,**kwargs)
    B=lambda x: P(x,bullet,bulletText="-")
    story=[]
    # Cover and purpose
    story += [Spacer(1,3.15*cm),P("VERICLAIM AI",ParagraphStyle("k",parent=sub,fontName="Helvetica-Bold",fontSize=12,textColor=TEAL)),Spacer(1,.2*cm),P("From Zero to Judge-Ready",title),P("A step-by-step book for understanding, operating, explaining and improving the vehicle-damage fraud-triage project.",sub),Spacer(1,.8*cm)]
    c=Table([[P("<b>For you</b><br/>Minimal prior knowledge is assumed. Every important term is defined before it is used.",body),P("<b>By the end</b><br/>You will be able to explain the system honestly, use the Model Lab, defend the model choices and answer reviewer questions.",body)]],colWidths=[8.15*cm,8.15*cm])
    c.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),MINT),("BOX",(0,0),(-1,-1),.8,TEAL),("INNERGRID",(0,0),(-1,-1),.35,TEAL),("TOPPADDING",(0,0),(-1,-1),12),("BOTTOMPADDING",(0,0),(-1,-1),12),("LEFTPADDING",(0,0),(-1,-1),12),("VALIGN",(0,0),(-1,-1),"TOP")]))
    story += [c,Spacer(1,.65*cm),P("The golden rule",h2),P("VeriClaim AI does not decide that a person committed fraud. It prioritizes an image for human review based on patterns learned from labelled examples. An investigator makes the final decision.",call),PageBreak()]
    story += [P("How this book is different",h1),P("This is not a short project summary. It is a learning path. First you learn the words. Then you learn the data. Then you learn how the models train. Only after that do you study the website, metrics, code and presentation. Read the 'Say it to a judge' boxes aloud.",body),P("Book map",h2)]
    for x in ["Part I - Problem, terminology and data", "Part II - The learning pipeline from pixels to probability", "Part III - Imbalance, training and evaluation", "Part IV - Website, model operation and code map", "Part V - Limitations, future work and judge defence"]: story.append(B(x))
    story += [P("Your study method",h2),P("For each chapter: (1) read the simple definition, (2) explain it without looking, (3) locate the related code or UI feature, and (4) answer the checkpoint question. Do not attempt to memorize every number at once; first understand the causal story.",call),PageBreak()]

    def chap(num,title_,why,steps,judge=None,diagram=None,warning_text=None):
        story.append(P(f"{num}. {title_}",h1)); story.append(P(f"<b>Why this matters:</b> {why}",body))
        if diagram: story.extend([diagram,Spacer(1,.2*cm)])
        for heading,content in steps:
            story.append(P(heading,h2))
            for item in content:
                story.append(B(item[2:]) if item.startswith("- ") else P(item,body))
        if warning_text: story.append(P(f"<b>Important caution:</b> {warning_text}",warning))
        if judge: story.append(P(f"<b>Say it to a judge:</b> {judge}",call))
        story.append(Spacer(1, .22*cm))

    chap(1,"What problem are we solving?","If you frame the problem incorrectly, every later model decision becomes confusing.",[("The real-world setting",["An insurer receives vehicle-damage claims. A claim may include one or more photos, documents and a customer statement. Manually reviewing every image in depth takes time.","Fraud investigation is not the same as damage classification. A damaged vehicle can be a genuine claim. The project therefore predicts review priority, not whether damage exists."]),("The technical task",["The supplied data gives one label for each training image: fraud or non-fraud. This makes the task <b>binary supervised image classification</b>.","Binary means two possible labels. Supervised means the training examples include the answer. Classification means choosing or scoring a category."]),("The desired output",["The model produces a fraud-risk probability from 0 to 1, then compares it to a chosen threshold.","The app turns that technical result into a clear operational message: 'Fraud - review recommended' or 'Non-fraud - no fraud flag'."]),],"'We built a human-led triage system. It ranks potentially suspicious photo evidence for staff review; it does not accuse a customer or automatically reject a claim.'",Pipeline(["Claim photo","Visual features","Risk evidence","Review queue","Human decision"],"The business outcome is faster, better-prioritized investigation - never an automatic verdict."))
    chap(2,"The vocabulary you need first","Knowing these words removes most of the mystery.",[("Core words",["<b>Dataset:</b> a collection of examples used for learning or evaluation.","<b>Image:</b> a grid of pixels. A pixel is a tiny colored square represented by numbers.","<b>Label or target:</b> the known answer attached to a training image. Here, target 1 means fraud and target 0 means non-fraud.","<b>Feature:</b> a useful numeric clue used by a model. Raw pixels are features; a CNN can make richer features.","<b>Model:</b> a mathematical function that turns features into a prediction.","<b>Parameter or weight:</b> an internal number the model changes while learning."]),("Words used after training",["<b>Inference:</b> using a saved trained model on a new uploaded image.","<b>Probability:</b> a score between 0 and 1. It is a model-estimated risk score, not a legal probability of guilt.","<b>Threshold:</b> the score boundary used to show a review flag.","<b>Ensemble:</b> several models combined so that the final result does not rely on only one model."])])
    chap(3,"Understand the supplied dataset","A model can learn only from what appears in its data. Start every ML project by inspecting the data rather than jumping into training.",[("Exact project schema",["Training images: 5,200 total. Fraud images: 200. Non-fraud images: 5,000. Fraud rate: 3.85%.","Supplied test images: 1,416 total. Fraud images: 93. Non-fraud images: 1,323. Fraud rate: 6.57%.","Each image has a binary target. Optional accident categories such as collision, weather or parked damage are not required because they are not consistently present in the supplied test set."]),("What to check in data exploration",["Count files and labels. Inspect image extensions, damaged files, dimensions, color formats and missing labels.","Look at examples from both classes. Ask whether labels appear trustworthy, whether photos have watermarks, repeated backgrounds or other shortcuts.","Check duplicates and near-duplicates. A nearly identical picture in training and test makes evaluation easier than real life."])],"'Our target is a binary dataset label. We deliberately keep damage-type information optional because it is unavailable for parts of the supplied test set.'")
    data_rows=[["Split","Total","Fraud","Non-fraud","Fraud percentage"],["Training","5,200","200","5,000","3.85%"],["Supplied test","1,416","93","1,323","6.57%"]]
    table=Table([[P(str(v),small) for v in row] for row in data_rows],colWidths=[3.2*cm,2.3*cm,2.4*cm,3*cm,3.2*cm],repeatRows=1)
    table.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),NAVY),("TEXTCOLOR",(0,0),(-1,0),colors.white),("BACKGROUND",(0,1),(-1,-1),PALE),("GRID",(0,0),(-1,-1),.35,colors.HexColor("#C7D5DB")),("ALIGN",(1,0),(-1,-1),"CENTER"),("TOPPADDING",(0,0),(-1,-1),7),("BOTTOMPADDING",(0,0),(-1,-1),7)]))
    story += [P("Dataset reference table",h2),table,PageBreak()]
    chap(4,"What is supervised learning?","This is the learning style used by VeriClaim. It is easiest to understand as practice with answers.",[("Flashcard analogy",["Imagine 5,200 flashcards. The front contains a photo. The back says fraud or non-fraud. The system sees the front, guesses the answer, looks at the back and measures its mistake.","After many flashcards, it sees a new photo without the answer. It makes its best estimate based on visual patterns it encountered during practice."]),("The six training actions",["1. Load a labelled training image.","2. Prepare it in the same size and format used by all other images.","3. Pass the image through the model to obtain a predicted fraud score.","4. Compare that prediction with the known label using a loss function.","5. Adjust internal weights to reduce future error.","6. Repeat across examples many times, then save the trained artifact."]),("What supervised learning cannot know",["It does not inspect insurance truth, customer intent, police reports or hidden context. It learns visual correlations with the dataset labels.","If labels are wrong, biased or incomplete, the model can repeat those weaknesses."])],"'We use supervised learning: historical labelled images teach the model which visual patterns were associated with fraud and non-fraud labels in this dataset.'",Pipeline(["Labelled photo","Model predicts","Compare answer","Update weights","Repeat"],"Training is the learning phase. Upload-time scoring is called inference."))
    chap(5,"How a photo becomes numbers","Computers do not see a car photo as humans do. They begin with numeric pixels.",[("Pixel representation",["A color image is commonly stored as three channels: red, green and blue. Each pixel therefore has three intensity values.","A photo can be very large. To keep the model consistent and fast, this project resizes each input to 224 x 224 pixels before EfficientNetV2B0 processes it."]),("Preprocessing",["Preprocessing means applying the same preparation rules to every image. It may include decoding, converting color format, resizing and normalization expected by the backbone.","Training and inference must use the same preprocessing. If training uses one size or color scaling and the website uses another, predictions become unreliable."]),("Feature extraction",["The CNN receives the prepared pixels and produces an <b>embedding</b>: a list of 1,280 numbers that summarize useful visual patterns.","An embedding is not a simple explanation such as 'scratch present'. It is a compact learned numeric representation that later models can read."])])
    chap(6,"Neural networks from scratch","A neural network is a flexible mathematical function that learns by changing many adjustable weights.",[("The artificial neuron",["A basic neuron receives input numbers, multiplies them by weights, adds them, and passes the result through an activation function. The activation allows the network to learn non-linear relationships.","A network contains many neurons organized in layers. Earlier layers create simple representations; later layers combine them into more abstract representations."]),("Convolutional neural network or CNN",["A CNN is built for images. Instead of treating every pixel independently, it uses small filters that inspect neighboring pixels together.","Early CNN layers learn edges, lines, colors and textures. Deeper layers learn combinations that may relate to parts, damage appearance, angle, background and composition."]),("Why two tire photos differ",["The system does not contain a rule saying 'tire photo equals fraud'. It considers a high-dimensional combination of learned patterns: texture, lighting, crop, background, image quality, damage appearance and similarity to labelled examples.","That is why a result must be treated as triage evidence and reviewed by a human."])])
    chap(7,"Why EfficientNetV2B0 is used","The backbone is the part of the system that turns pixels into strong visual features. We chose a practical modern CNN rather than training a huge image model from nothing.",[("What EfficientNetV2B0 does",["It receives a 224 x 224 image and produces a 1,280-number embedding. This embedding feeds the fraud classifiers.","It is a CNN optimized for good accuracy with relatively modest compute. This makes it a strong hackathon baseline that can run in a local web workflow."]),("Transfer learning",["The CNN starts with ImageNet-pretrained weights. ImageNet pretraining gives general knowledge of edges, textures and visual structure.","No external insurance or claim dataset was added. General ImageNet visual pretraining is disclosed; fraud learning comes from the supplied hackathon images."]),("Why not use every popular model",["YOLO needs damage-location bounding-box labels to be fully justified. GANs need careful validation and can complicate a small-data project. Very large models require more compute and can overfit.","EfficientNetV2B0 gives a balanced choice: strong visual representation, manageable complexity and an explainable role in the architecture."])],"'We selected EfficientNetV2B0 as a lightweight transfer-learning backbone. It extracts strong general visual features while the fraud-specific layers learn only from the supplied images.'")
    chap(8,"Class imbalance: the central data problem","Rare fraud labels create a trap: a model can look accurate while being useless for fraud detection.",[("The always-normal trap",["Because 5,000 of 5,200 training images are non-fraud, a model that predicts non-fraud for every photo would be about 96% accurate on the training distribution.","But it would find zero fraud images. This proves that accuracy alone is not an appropriate success measure for this task."]),("The metrics that matter",["<b>Recall:</b> out of all actual fraud-labelled cases, how many did the model flag? High recall means fewer suspicious cases are missed.","<b>Precision:</b> out of all flagged cases, how many were actually fraud-labelled? Higher precision means less wasted investigation work.","<b>F1:</b> balances recall and precision. <b>F2:</b> gives recall extra importance. <b>PR AUC:</b> summarizes precision-recall quality across thresholds and is especially useful for rare classes."]),("The operational trade-off",["Improving recall usually means flagging more cases, including some normal ones. Improving precision often means stricter flags, which can miss fraud.","The correct balance is a business decision based on investigator capacity and the cost of missed fraud."])],"'We do not celebrate accuracy alone. We measure recall, precision, F1, F2 and PR AUC because the fraud class is rare.'")
    chap(9,"Exactly how our imbalance handling works","We use two complementary approaches. Neither adds a new external dataset and neither permanently removes normal evidence.",[("Method 1: class weighting",["During MLP training, a fraud error receives about 25 times the training importance of a normal error. In notation, a normal sample has weight about 1 and a fraud sample has weight about 25.","This is called <b>cost-sensitive learning</b> or <b>class weighting</b>. It changes the penalty the optimizer sees. It does not create 25 copied image files.","Effect: if the model misses one rare fraud example, training reacts much more strongly than it would for one normal example."]),("Method 2: rotating 1:8 Extra Trees",["There are 20 rotating balanced Extra Trees learners. Every learner receives every fraud image plus a different temporary group of normal images at an approximate ratio of 1 fraud to 8 normal images.","Learner A sees all fraud images plus normal group A. Learner B sees all fraud images plus normal group B. The final rotating-tree score averages their predictions.","Effect: every individual learner faces a less overwhelming imbalance, while the full ensemble still uses the available normal images across rotations."]),("Why it is better than using equal count data",["Training with equal fraud and normal counts would discard most normal examples or repeat fraud photos heavily. Testing with equal counts would misrepresent the real supplied class mix.","Our method gives fraud more learning importance while retaining a realistic imbalanced test evaluation."])],"'We balanced learning, not reality: fraud mistakes are weighted about 25:1 and rotating tree learners use 1:8 subsets. Evaluation keeps the supplied imbalance.'",Pipeline(["200 fraud\nphotos","Weight fraud\nx25","20 rotating\n1:8 learners","Average votes","Realistic test\nevaluation"],"The goal is to prevent an easy 'always normal' model without pretending the world is 50:50."))
    chap(10,"The non-neural models: MLP, Extra Trees and logistic regression","The system is hybrid because different algorithms contribute different strengths.",[("MLP ensemble",["An MLP, or multilayer perceptron, is a smaller neural network. It reads the 1,280-number CNN embedding and estimates fraud likelihood.","The project uses five MLPs. Averaging multiple MLP predictions reduces dependence on one random initialization or local training variation."]),("Extra Trees ensemble",["A decision tree learns a sequence of numeric questions. Extra Trees build many randomized trees and average them. They can capture feature interactions in a way different from MLPs.","The project contains full-data Extra Trees and rotating balanced Extra Trees. Their diversity makes the final ensemble less dependent on one kind of decision boundary."]),("Logistic regression",["Logistic regression is a simple, strong model that turns combined signals into a probability. Here it is used for fusion and calibration rather than raw-image recognition.","Its value is transparency and stable probability-style output when combining model scores."])])
    chap(11,"Fraud archive similarity: pHash","The project adds a separate visual-similarity signal. It is not a classifier by itself.",[("Perceptual hash",["A normal file hash changes completely if an image is resized. A perceptual hash, or pHash, is designed so visually similar images often have similar short signatures.","The system calculates pHash-style visual signatures and compares the uploaded image to an archive of fraud-labelled examples."]),("How it contributes",["A close match can be evidence worth showing an investigator: perhaps it is a reused photo, the same damage scene, or simply a visually similar image.","Archive similarity becomes one input to the fusion model. It should never be interpreted as proof of a duplicated fraudulent claim without human investigation."]),("Why this is a standout feature",["It goes beyond a black-box yes/no output. It gives a reviewer an evidence direction: 'this image looks close to archived labelled fraud evidence'."])],"'Twin Radar is a visual-similarity aid. It helps an investigator discover close archive matches; it does not automatically declare a duplicate or a fraud.'")
    chap(12,"Fusion and probability calibration","The system must combine multiple imperfect signals into one operational score.",[("Fusion",["Inputs to the final fusion layer include CNN/MLP evidence, Extra Trees evidence and fraud-archive similarity. Logistic regression learns how to combine these inputs from labelled examples.","Fusion is helpful because a photo can have one strong signal and one weak signal. The final result considers them together instead of letting any single subsystem decide alone."]),("Calibration",["Raw model scores are often overconfident or underconfident. Calibration maps raw scores to probabilities that better match observed outcomes on held-out data.","This project uses Platt calibration, which fits a logistic mapping over scores. Calibration makes a score more useful for thresholding, but it does not turn it into proof."]),("Threshold",["The current operating threshold is 0.0612. A calibrated probability at or above it produces a review recommendation.","The threshold is low because the project prioritizes recall. It will cause some normal claims to be sent for review. It must be documented with the model version and revisited if workload changes."])],"'The score is calibrated and thresholded for review workload. It is not a probability of guilt and it is not an automatic decision.'")
    chap(13,"The complete end-to-end pipeline","This chapter links every component into one single story.",[("Upload-time inference steps",["1. A user uploads an image through the Model Lab or claim workflow.","2. The app validates and decodes the image. Optional damage context can be recorded but is not required.","3. The image is resized to 224 x 224 and prepared exactly as it was during training.","4. EfficientNetV2B0 creates a 1,280-number visual embedding.","5. Five MLPs score the embedding. Full and rotating Extra Trees score it too.","6. pHash compares the photo with archived fraud-labelled visual evidence.","7. Fusion combines all signals. Platt calibration produces the displayed fraud-risk probability.","8. The application compares risk with 0.0612 and shows the review label plus supporting evidence.","9. A human investigator uses this as one part of a broader claim decision."]),("Training versus inference",["Training changes weights using labelled images. Inference never changes the model; it only uses saved artifacts to score a new photo.","The saved files are the hybrid artifact <b>models/efficientnet_hybrid/vericlaim_model.joblib</b> and the CNN backbone <b>models/efficientnet_hybrid/efficientnetv2b0_backbone.keras</b>."])],"'The same preprocessing is used at training and prediction time. That consistency is essential for reliable results.'",Pipeline(["Upload","Resize 224x224","EfficientNet\nembedding","MLP + trees\n+ pHash","Fusion +\ncalibration","Human review"],"Every result passes through the same controlled pipeline, from pixels to a human review recommendation."))
    chap(14,"Understand the test results step by step","A judge should hear both the good results and the mistakes. Honest evaluation is a strength.",[("Current EfficientNet hybrid",["Accuracy: 96.12%. Balanced accuracy: 94.42%. Fraud recall: 92.47%. Precision: 64.18%. F1: 75.77%. F2: 84.98%. ROC AUC: 0.9759. PR AUC: 0.9048.","Confusion matrix: 86 true positives, 7 false negatives, 48 false positives and 1,275 true negatives."]),("Read the confusion matrix",["True positive: a fraud-labelled test image correctly flagged. There are 86.","False negative: a fraud-labelled image that the model did not flag. There are 7. These are important misses to study.","False positive: a non-fraud-labelled image flagged for review. There are 48. These create investigator workload but are safer than automatic denials.","True negative: a non-fraud-labelled image correctly not flagged. There are 1,275."]),("Previous vs current",["Previous MLP hybrid: 83.33% accuracy, 81.72% recall, 25.76% precision and 0.6438 PR AUC.","Current EfficientNet hybrid: 96.12% accuracy, 92.47% recall, 64.18% precision and 0.9048 PR AUC.","The current model improves both recall and precision on this supplied evaluation split."])],"'On the supplied test split we correctly flagged 86 of 93 fraud-labelled images, missing 7. We also sent 48 normal images for review. That is the explicit triage trade-off.'")
    chap(15,"Leakage: the result you must disclose","Leakage is one of the most important expert concepts. Hiding it would make the presentation weaker; explaining it makes the team credible.",[("What we found",["A perceptual audit found 53.7% of supplied test images were close visual matches to training images. It also found 261 identical perceptual hashes.","This does not necessarily mean files are exact duplicates, but it means train and test may contain very visually related images."]),("Why it matters",["A model may perform well partly because it sees a near-copy of a training photo in testing. In production, completely new scenes may be harder.","Therefore the reported metrics are valid for the supplied split but may be optimistic for a clean real-world deployment."]),("Correct next experiment",["Create duplicate or near-duplicate clusters using visual hashes or embeddings. Keep every cluster entirely in either training or evaluation, never both.","Then retrain and report grouped-split metrics. This is stronger evidence of generalization."])],"'We explicitly audited leakage. Our next evaluation will use duplicate-aware grouped splits, because that is a more rigorous estimate of performance on truly unseen claims.'",warning_text="Do not claim 96.12% is a production accuracy guarantee. It is a result on the supplied hackathon split, which has near-duplicate visual relationships.")
    chap(16,"Website and user journey","A good ML model needs a usable workflow. The website turns a model file into a demonstrable product.",[("Customer portal concept",["Homepage navigation: Home, Claims, Policies, Contact and Login. A customer can start a claim, upload image/document/video evidence, track status and receive support.","Claim tracking should be understandable: Submitted, Under Review, Approved or Rejected, then Settled. The customer portal must avoid showing accusatory language."]),("Staff portal concept",["Staff see pending claims, fraud-review alerts, communication logs, verification workflow and reporting. Role-based access protects sensitive claim data.","AI results should show the score, threshold, model version and evidence cues, then provide an explicit investigator action and audit trail."]),("Model Lab",["Model Lab is the controlled demo portal. Upload an image to test the previous and current models, see probability and see whether the active threshold produces a fraud-review flag.","It is useful for demonstrations, regression testing and explaining model upgrades. Test with known images, not random internet photos, when showing a judge."])])
    chap(17,"Map the theory to actual project code","This bridges beginner understanding with developer-level credibility.",[("Core training file",["<b>src/vericlaim/train_efficientnet_hybrid.py</b> trains the system. It loads image data, obtains EfficientNet embeddings, trains MLP and Extra Trees ensembles, creates archive features, fuses scores, calibrates probability and saves artifacts.","Read this file in execution order. Do not try to understand each line first; identify the stages: data loading, feature creation, individual models, fusion, calibration, metric reporting and saving."]),("Application file",["<b>src/vericlaim/app.py</b> connects web requests to the trained model. It handles upload-time prediction and returns data the interface can display.","The website should load the current saved model artifact. If you retrain, verify the artifact location and restart the app if necessary."]),("Documentation",["<b>docs/model_card.md</b> is the honest contract: intended use, evaluation, limitations and risks.","<b>docs/architecture.md</b> explains system components. <b>docs/developer_study_guide.md</b> is the editable project-learning source."])],"'The code reflects the same architecture story we present: CNN embedding, ensemble scores, archive similarity, fusion, calibration and human review.'")
    chap(18,"Disciplined retraining workflow","Rigorous training is not simply running an algorithm again. It is a controlled experiment with a baseline, a change and comparable evaluation.",[("Before training",["Record baseline model version, date, data counts, threshold and all metrics. Without a baseline you cannot prove an improvement.","Check labels, unreadable files, class counts, duplicate risk and preprocessing consistency."]),("During training",["Change one variable at a time: class weight, non-fraud ratio, CNN freezing strategy, augmentation policy or threshold selection.","Never use the final test split repeatedly to choose model settings. This leaks evaluation information into your choices.","Log seeds, package versions, training command and artifact paths so another developer can reproduce the run."]),("After training",["Compare accuracy, recall, precision, F1, F2, ROC AUC, PR AUC, calibration and the confusion matrix. Inspect false positives and false negatives visually.","Test website integration with known samples. Confirm that the UI is loading the intended new artifact, not an old cached model."])],"'We improve the system through controlled experiments. Each run is versioned, evaluated on multiple metrics and checked in the website before we claim an upgrade.'")
    chap(19,"How to answer hard judge questions","Strong reviewers will test whether you understand choices and limitations. These are answers you should understand, not memorize word for word.",[("Question: Is this a neural network model?",["Yes. EfficientNetV2B0 is a convolutional neural network, and the MLP ensemble is also neural-network based. The project also uses classical ML components: Extra Trees and logistic regression."]),("Question: Why hybrid instead of only EfficientNet?",["EfficientNet creates strong visual features. MLPs and trees use those features differently, while archive similarity adds an interpretable evidence path. Fusion combines diverse signals and can be more robust than a single score."]),("Question: Why not SMOTE?",["SMOTE is mainly designed for tabular numeric data. Generating synthetic image embeddings can create unrealistic boundaries; generating synthetic claim photos has extra risk. We instead use class weighting and rotating balanced ensembles without adding data."]),("Question: Is weighting better than augmentation?",["They solve different problems. Weighting says rare fraud mistakes matter more. Augmentation creates transformed training views to improve robustness. Our current system uses weighting and rotating sampling; carefully validated augmentation is future work."]),("Question: What would you add next?",["Duplicate-aware grouped validation first, because honest evaluation comes before more complexity. Then Grad-CAM explanations, out-of-distribution warnings, controlled augmentation and damage localization if suitable labels are obtained."])])
    chap(20,"Your presentation and demo rehearsal plan","The final skill is communicating the project as one clear story.",[("Two-minute structure",["0:00-0:20: State the real problem - rare suspicious vehicle claims need review prioritization, not automatic accusations.","0:20-0:45: Describe supplied dataset and severe imbalance: 200 fraud vs 5,000 non-fraud training images.","0:45-1:15: Explain solution: EfficientNet CNN embedding plus MLP, Extra Trees, archive similarity, fusion and calibration.","1:15-1:35: Explain balancing: about 25:1 fraud class weighting plus 20 rotating 1:8 Extra Trees learners.","1:35-1:50: Show Model Lab upload and human-review result.","1:50-2:00: Give metrics and disclose leakage limitation plus next step."]),("Final checklist",["Can you explain the difference between accuracy, recall and precision?","Can you say why 96% accuracy could be useless on this imbalance?", "Can you explain the exact 25:1 and 1:8 balancing methods?", "Can you explain why the model does not prove fraud?", "Can you identify the current biggest evaluation risk?", "Can you show the Model Lab and describe every output field?"])],"'Our innovation is not just a classifier. It is a transparent, human-led evidence-triage workflow with imbalance-aware training, archive similarity and an honest evaluation story.'")
    chap(21,"The small amount of mathematics behind the model","You do not need advanced mathematics to explain the project, but these ideas help you speak precisely.",[("Probability and sigmoid",["The final logistic model produces a number called z, then uses a sigmoid function: probability = 1 / (1 + e to the power of -z). This converts any real number into a score between 0 and 1.","If z is large and positive, the probability approaches 1. If z is negative, it approaches 0. The threshold then determines the operational review label."]),("Loss and weighting",["For binary labels, training commonly uses binary cross-entropy loss. It penalizes a confident wrong prediction more than an uncertain one.","Class weighting multiplies the fraud part of the loss by approximately 25. Conceptually: total loss = 25 times fraud loss + 1 times normal loss. This explains why the optimizer focuses more on rare fraud mistakes."]),("Confusion-matrix formulas",["Recall = true positives / (true positives + false negatives). Here: 86 / (86 + 7) = 92.47%.","Precision = true positives / (true positives + false positives). Here: 86 / (86 + 48) = 64.18%.","Accuracy = all correct / all test images. It is not sufficient alone because normal images dominate the data."])],"'The mathematics supports our business choice: we increase the training penalty for missed fraud and measure the resulting recall-precision trade-off.'")
    chap(22,"Data augmentation, SMOTE and class weighting","These methods are often confused. Understanding their difference will make your technical explanation much stronger.",[("Data augmentation",["Augmentation creates safe transformed views of existing images during training, for example mild rotation, brightness shift, crop or horizontal flip. It can improve robustness to camera angle and lighting.","Risk: if transformations are unrealistic for car damage, the model learns artifacts. Augmentation must be used only on training data and validated carefully."]),("SMOTE",["SMOTE creates synthetic points between minority examples. It is mainly designed for tabular numeric features, not original images.","Applying SMOTE to image embeddings can make points that do not correspond to a realistic photograph. Generating synthetic insurance images may introduce visual artifacts or unrealistic fraud cues."]),("Why our current approach is appropriate",["Class weighting is simple, controlled and directly addresses rare labels. Rotating ensembles expose all normal examples over time without inventing samples.","Future work can add modest, documented image augmentation. It should be evaluated using duplicate-aware validation, not just a higher score on the current split."])],"'Weighting changes how much each mistake matters. Augmentation changes the training view of an image. SMOTE synthesizes numeric points. We use weighting and rotating sampling because they are safest for this supplied image dataset.'")
    chap(23,"How to investigate a wrong prediction","A wrong prediction is not just a failure; it is training evidence for the next iteration.",[("Start with the result type",["False positive: a normal-labelled image was flagged. Ask if it is visually unusual, close to a fraud archive image, poorly lit, cropped strangely or potentially mislabelled.","False negative: a fraud-labelled image was missed. Ask whether it is visually unlike the training fraud examples, tiny, blurred, damaged differently or affected by a label issue."]),("Create an error-analysis table",["For each error, record image ID, true label, predicted probability, threshold, MLP score, tree score, archive-similarity score, image condition and investigator notes.","Group recurring patterns. For example, if many false negatives are low-light bumper images, then a carefully validated low-light augmentation or additional labelled data may be justified."]),("Do not overreact",["Do not change the full architecture because of one surprising tire image. Look for repeated error patterns across a sufficiently large sample.","Do not tune threshold using only a handful of examples. Use a validation procedure and report the impact on recall and precision."])])
    chap(24,"Explainability: what we can and cannot show today","Explainability builds reviewer trust, but it must be honest. The current system has evidence signals, not a complete visual explanation map.",[("Current explanations",["The app can communicate model probability, threshold, output label, model version and archive-similarity evidence. Claim DNA Passport makes this review record explicit.","Twin Radar can show that an image is visually close to archived fraud-labelled examples. That gives an investigator a direction for review."]),("Grad-CAM as future work",["Grad-CAM is a technique that creates a heatmap over an image, indicating regions that most influenced a CNN class score. It can help a reviewer ask: did the model focus on the damage area or on an irrelevant background?", "A heatmap is not proof of causal reasoning. It is a diagnostic tool and must be evaluated for stability and usefulness."]),("Out-of-distribution warning",["An out-of-distribution image is unlike the training data, such as a completely unrelated tire product photo or a different image style. A mature system should warn: 'This image is unlike the training distribution; confidence may be unreliable.'", "This directly addresses unexpected Model Lab behavior on random images."])],"'Today we expose probability, threshold, model version and archive evidence. Our next explainability upgrade is Grad-CAM plus an out-of-distribution warning, not false certainty.'")
    chap(25,"Production architecture and security","The hackathon website is a demo. A real claims platform needs stronger controls around people, evidence and model operations.",[("Recommended production flow",["Customer web or mobile app -> authenticated API -> secure evidence storage -> malware/file validation -> model scoring service -> case-management queue -> investigator decision -> immutable audit record.","Separate model service from web UI. This allows independent scaling, safer updates and clearer monitoring."]),("Security essentials",["Use secure authentication, role-based access control, encrypted storage and transport, upload size/type validation and server-side file scanning.","Avoid exposing customer images, personal data or model artifacts in browser logs. Limit staff access to cases needed for their role."]),("Auditability",["Store timestamp, input file identifier, model version, preprocessing version, raw score, calibrated score, threshold, evidence signals, reviewer action and reason for override.","Audit records protect customers, investigators and the project team because every recommendation can be traced and reviewed."])])
    chap(26,"Production monitoring","A model is not finished when it is deployed. It must be monitored because the data and workflow can change.",[("What can drift",["Image style can change: new phone cameras, repair-shop photo formats, lighting, resolution or compression. Claim patterns and fraud methods can also change.","Data drift means inputs look different. Concept drift means the relationship between visual patterns and fraud labels changes."]),("What to track",["Upload volume, flag rate, review workload, accepted/rejected outcomes, false-positive rate, recall on eventually confirmed labels, calibration quality and the fraction of out-of-distribution warnings.","Compare these metrics by time period, channel, geography only where lawful, and image quality. Watch for sudden shifts after a camera or app update."]),("Human feedback loop",["Allow investigators to record whether a flag was useful and why. Periodically review those outcomes, improve labels and retrain only with governance approval.","Do not automatically retrain from every reviewer action; review labels can themselves be biased or inconsistent."])])
    chap(27,"Alternative models and why they are future experiments","Knowing alternatives lets you justify the present choice without claiming it is the only possible solution.",[("Custom CNN and MobileNetV2",["A custom CNN is a good simple benchmark but often learns weaker features with limited data. MobileNetV2 is fast and suitable for mobile deployment; it is a valid baseline or deployment alternative."]),("ResNet, DenseNet and ConvNeXt",["ResNet50 is a proven residual CNN, DenseNet reuses features through dense connections, and ConvNeXt is a modern CNN design. All can be compared under exactly the same grouped validation protocol.","A bigger model is not automatically better. With only 200 fraud training images, high-capacity models can overfit or learn data shortcuts."]),("YOLO and metadata fusion",["YOLO is for object detection and could localize damage regions only when you have bounding-box labels for damage. It is not justified merely because a photo is available.","A fusion model can combine image embedding with lawful claim metadata, but metadata must be available at prediction time and checked carefully for target leakage and privacy."])],"'EfficientNetV2B0 is our current best practical baseline. Other architectures are controlled future experiments, not automatic upgrades.'")
    chap(28,"Expanded judge-question bank","Use these as practice prompts. Explain the reason, the trade-off and the limitation in every answer.",[("Data and model questions",["<b>What is the target variable?</b> The supplied binary fraud label for each image: fraud = 1, non-fraud = 0.","<b>What features does the model use?</b> A CNN-derived 1,280-number embedding, scores from MLP and Extra Trees ensembles, and visual archive similarity. It does not require damage type.","<b>Why is the model supervised?</b> Because training images come with known fraud/non-fraud answers.","<b>Why use transfer learning?</b> The fraud dataset is small. ImageNet pretraining supplies general visual feature knowledge, while fraud-specific learning stays within the supplied data."]),("Evaluation and ethics questions",["<b>How do you know it works?</b> We use the supplied test split and report recall, precision, F1, F2, PR AUC and the confusion matrix, not only accuracy.","<b>What is the biggest risk?</b> Near-duplicate visual relationships between train and test can inflate metrics. We disclose it and propose grouped validation.","<b>Could this harm customers?</b> Yes, if misused as an automatic decision. That is why our design is review-only, records evidence and retains investigator override."]),("Product questions",["<b>What makes it unique?</b> Hybrid evidence fusion, imbalance-aware training, archive similarity, Claim DNA Passport, Model Lab comparison and explicit human-led governance.","<b>How would you scale it?</b> Separate web app, secure storage, model-scoring service, queueing, audit logs, monitoring and a governed feedback loop."])])
    chap(29,"Training script walkthrough: from command to artifact","This chapter is tied directly to src/vericlaim/train_efficientnet_hybrid.py, so you can read the code without guessing what each stage means.",[("Stage A: arguments and discovery",["The command-line arguments define data location, output directory, cache directory, image size 224, five validation folds, perceptual distance 6, recall target 0.99, 300 full-data trees, 100 balanced trees per fold and a non-fraud ratio of 8.","discover(data_root, 'train') and discover(data_root, 'test') locate the Fraud and Non-Fraud folders and return paths plus binary labels. The script stops early if either split is missing."]),("Stage B: forensic and CNN features",["extract_many creates the existing forensic feature set and perceptual hashes. build_perceptual_groups turns hashes into groups so similar training images can be kept apart during folds.","TensorFlow loads an ImageNet-pretrained EfficientNetV2B0 with include_top=False, average pooling and preprocessing included. backbone.trainable = False freezes it: no ImageNet backbone weights are changed in this run.","extract_embeddings decodes an image, pads/resizes it to 224 x 224, batches 32 images, runs backbone.predict, and caches the embeddings. Caching prevents repeated expensive extraction when file paths and settings are unchanged."]),("Stage C: fold-level base models",["StratifiedGroupKFold creates five folds. Stratified means it preserves fraud/non-fraud proportions as much as possible. Grouped means perceptually related photos should not split across fit and validation portions.","For each fold, the script fits a 300-tree ExtraTreesClassifier with balanced_subsample weighting; rotating balanced tree models using the 1:8 ratio; a neural model from the existing feature pipeline; and a class-balanced logistic CNN head on CNN embeddings.","Each model predicts the held-out validation fold. These are out-of-fold predictions: a training image is scored by a model that did not train on that image. This is essential for honest stacking."]),("Stage D: fusion, calibration and saving",["stack_features combines six evidence columns: full-tree score, rotating-tree score, MLP score, CNN score, fraud archive similarity, legitimate archive similarity and their difference.","A logistic stacker learns how to combine those columns. A separate logistic calibrator fits Platt scaling on out-of-fold stacker scores. The script selects review, investigate and classification thresholds, records metrics and audits duplicate risk.","Finally it saves vericlaim_model.joblib, efficientnetv2b0_backbone.keras and model_metrics.json. The website must load these matching artifacts."])])
    chap(30,"Validation design: why folds and out-of-fold predictions matter","This is the difference between a model that merely fits data and a model evaluation you can defend.",[("The danger of training-score evaluation",["If a model predicts the same images it learned from, it can memorize details. A high training score does not prove it will work on new uploads.","Therefore the script uses held-out fold predictions. Each training example gets an out-of-fold score from a model trained without that example."]),("Why stacking needs OOF scores",["If the fusion model learned from base-model scores that were created on the same images those base models trained on, the fusion layer would see overly optimistic inputs. This is called stacking leakage.","The script avoids that by assembling oof_full, oof_balanced, oof_neural, oof_cnn and oof_archive. The fusion and calibration stages learn from these held-out predictions."]),("What grouped folds protect",["Perceptually close image clusters may depict the same scene, the same vehicle or nearly identical crops. Standard random folds can place close versions in both fit and validation data.","StratifiedGroupKFold is better because it keeps a cluster together. It is still a mitigation, not proof that the supplied official test split has no similar images."])],"'Our fusion layer learns from out-of-fold evidence, not scores produced on images the base model already trained on. That prevents a common stacking leakage mistake.'")
    chap(31,"Hyperparameter reference: what can be changed and what it changes","A hyperparameter is a setting chosen by developers before or during training, rather than a weight learned automatically from data.",[("Image and backbone settings",["image_size=224 controls the input size. Larger images can preserve more detail but require more compute and may not improve results on limited data.","The backbone is frozen. Unfreezing selected CNN layers could adapt visual features to the dataset, but increases overfitting risk. It should be tried only with strict grouped validation."]),("Ensemble settings",["full_trees=300 controls how many trees are in each full-data Extra Trees forest. More trees can stabilize estimates but increase training time and artifact size.","balanced_trees=100 and validation_folds=5 lead to many balanced learners. nonfraud_ratio=8 controls the temporary class mix each learner sees. A smaller ratio focuses more on fraud; a larger ratio presents more normal variation."]),("Decision settings",["recall_target=0.99 influences the review threshold chosen from out-of-fold training predictions. It reflects a policy choice: prioritize catching fraud-labelled examples at the cost of more review.","perceptual_distance=6 controls which pHashes count as close when creating similarity groups. Changing it changes both leakage grouping and archive-similarity interpretation."]),("How to tune responsibly",["Choose a small planned grid, such as nonfraud ratio 4, 8 and 12, then compare grouped validation recall, precision, PR AUC, calibration and workload. Do not run dozens of experiments against the final test set.","Keep a table containing experiment ID, code version, settings, random seed, threshold, metrics, runtime and final decision."])])
    chap(32,"Practical lab workbook: learn by doing","Use these exercises in sequence. They turn passive reading into project skill.",[("Lab 1: inspect the dataset",["Count Fraud and Non-Fraud images in train and test. Calculate 200 / 5,200 and explain why it is 3.85%.","Open 10 images from each class. Write down visual differences you notice, but label them as hypotheses rather than facts. Ask what shortcuts a model could exploit."]),("Lab 2: explain one prediction",["In Model Lab, upload a known project image. Record probability, displayed label, threshold, archive evidence and model version.","Explain its path aloud: upload -> resize -> CNN embedding -> ensemble scores -> archive similarity -> fusion -> calibration -> threshold -> human review. Do not say the system 'knows' fraud."]),("Lab 3: calculate metrics",["Using true positives 86, false negatives 7 and false positives 48, calculate recall and precision manually. Then explain the difference in one sentence.","Change only the threshold in a controlled analysis if the app supports it. Predict before looking: lower threshold should normally increase recall and decrease precision."]),("Lab 4: inspect code",["Open train_efficientnet_hybrid.py. Locate extract_embeddings, fit_cnn_head, stack_features, StratifiedGroupKFold, the fold loop, the stacker, calibrator and artifact save call.","For each, write one plain-English sentence of purpose. This is the best way to become credible in a code review."]),("Lab 5: deliver a review",["Present the two-minute story to another person. Ask them to challenge you on imbalance, wrong tire images, leakage and customer harm. Revise your explanation until it is clear without jargon."])])
    story += [P("Final study checklist",h1),P("You have reached the end when you can explain this complete sentence without notes:",h2),P("'VeriClaim AI uses supervised learning on the supplied imbalanced vehicle-damage dataset. EfficientNetV2B0 converts a photo into a 1,280-number embedding; MLP and Extra Trees ensembles score it; pHash provides fraud-archive similarity; a logistic fusion model and Platt calibration produce a probability; a recall-aware threshold routes the claim for human review. We handle imbalance through approximately 25:1 fraud class weighting and rotating 1:8 tree learners, but we disclose near-duplicate leakage risk and do not treat model output as a fraud verdict.'",call),P("Next: open the website, explain the pipeline while clicking through Model Lab, then read <b>train_efficientnet_hybrid.py</b> side-by-side with Chapters 13, 17, 18 and 29.",body)]
    doc=SimpleDocTemplate(str(OUT),pagesize=A4,rightMargin=1.7*cm,leftMargin=1.7*cm,topMargin=2.15*cm,bottomMargin=1.8*cm,title="VeriClaim AI From Zero to Judge Ready Masterclass",author="VeriClaim AI Hackathon Team")
    doc.build(story,onFirstPage=header,onLaterPages=header)
    print(OUT)

if __name__=="__main__": build()
