"""Generate expanded backend developer learning guide."""
from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "output" / "pdf" / "VeriClaim_AI_Backend_Developer_Master_Guide.pdf"
def P(t,s): return Paragraph(t,s)
def diagram(labels,s):
    return Table([[P(x,s["BTFlow"]) for x in labels]], colWidths=[17*cm/len(labels)]*len(labels), style=TableStyle([
      ("BACKGROUND",(0,0),(-1,-1),colors.HexColor("#e9f3ec")),("GRID",(0,0),(-1,-1),.5,colors.HexColor("#83ab98")),
      ("VALIGN",(0,0),(-1,-1),"MIDDLE"),("LEFTPADDING",(0,0),(-1,-1),7),("RIGHTPADDING",(0,0),(-1,-1),7),("TOPPADDING",(0,0),(-1,-1),9),("BOTTOMPADDING",(0,0),(-1,-1),9)]))
def code(t,s):
    return Table([[P(t.replace("\n","<br/>"),s["BTCode"])]], colWidths=[17*cm], style=TableStyle([
      ("BACKGROUND",(0,0),(-1,-1),colors.HexColor("#10251e")),("BOX",(0,0),(-1,-1),.4,colors.HexColor("#34584a")),
      ("LEFTPADDING",(0,0),(-1,-1),10),("RIGHTPADDING",(0,0),(-1,-1),10),("TOPPADDING",(0,0),(-1,-1),8),("BOTTOMPADDING",(0,0),(-1,-1),8)]))

def build():
  OUT.parent.mkdir(parents=True,exist_ok=True)
  ss=getSampleStyleSheet()
  ss.add(ParagraphStyle(name="BTTitle",parent=ss["Title"],fontName="Helvetica-Bold",fontSize=27,leading=33,textColor=colors.HexColor("#073d2c"),spaceAfter=12))
  ss.add(ParagraphStyle(name="BTSub",parent=ss["BodyText"],fontSize=13,leading=20,textColor=colors.HexColor("#426457"),spaceAfter=14))
  ss.add(ParagraphStyle(name="BTH1",parent=ss["Heading1"],fontName="Helvetica-Bold",fontSize=20,leading=26,textColor=colors.HexColor("#073d2c"),spaceAfter=10))
  ss.add(ParagraphStyle(name="BTH2",parent=ss["Heading2"],fontName="Helvetica-Bold",fontSize=11,leading=14,textColor=colors.HexColor("#0d6548"),spaceBefore=8,spaceAfter=3))
  ss.add(ParagraphStyle(name="BTBody",parent=ss["BodyText"],fontSize=10.2,leading=15,textColor=colors.HexColor("#20362d"),spaceAfter=7))
  ss.add(ParagraphStyle(name="BTBullet",parent=ss["BodyText"],leftIndent=15,firstLineIndent=-10,fontSize=9.55,leading=14,textColor=colors.HexColor("#20362d"),spaceAfter=3))
  ss.add(ParagraphStyle(name="BTFlow",parent=ss["BodyText"],alignment=TA_CENTER,fontName="Helvetica-Bold",fontSize=8.3,leading=11,textColor=colors.HexColor("#073d2c")))
  ss.add(ParagraphStyle(name="BTCallout",parent=ss["BodyText"],backColor=colors.HexColor("#f2f8f4"),borderColor=colors.HexColor("#b6d6c1"),borderWidth=.6,borderPadding=9,fontSize=9.7,leading=14,textColor=colors.HexColor("#1d4937"),spaceBefore=7,spaceAfter=9))
  ss.add(ParagraphStyle(name="BTCode",fontName="Courier",fontSize=7.35,leading=9.5,textColor=colors.HexColor("#edf7ef")))
  def chapter(num,title): return [P("CHAPTER "+num,ss["BTH2"]),P(title,ss["BTH1"])]
  def section(head,text): return [P(head,ss["BTH2"]),P(text,ss["BTBody"])]
  def bullets(items): return [P("- "+x,ss["BTBullet"]) for x in items]
  story=[Spacer(1,2.1*cm),P("VERICLAIM AI",ss["BTH2"]),P("Backend Engineer Master Guide",ss["BTTitle"]),P("A detailed, beginner-friendly handbook for learning, understanding and confidently explaining the backend of the VeriClaim AI insurance-fraud triage project.",ss["BTSub"]),diagram(["Web interface","Python HTTP API","Validation + access","Model service","Human review workflow"],ss),Spacer(1,.6*cm),P("How to use this book",ss["BTH2"]),P("<b>Read it in order.</b> Each chapter introduces an idea, connects it to the real project, shows the request flow, then gives a practical exercise. Your goal is to explain what happens to one image and one claim from the moment a user clicks Submit.",ss["BTCallout"]),P("By the end you will be able to run the real service, trace an API request, add an endpoint safely, explain the AI integration without overclaiming, and describe how the hackathon prototype evolves into a production system.",ss["BTBody"]),PageBreak()]

  chapters=[
  ("1","Backend foundations: what your role is",[
   ("The plain-English meaning","The frontend is the visible dashboard that people click. The backend is the trusted coordinator behind it. A browser can be modified by a user, so it cannot be the final authority. The backend receives requests, checks them, chooses what work is allowed, calls the model, maintains case workflow state and returns a stable response."),
   ("What VeriClaim's backend owns","VeriClaim's server handles identity, image/evidence intake, fraud-risk triage, drafts, claim workflow, messages, notifications and PDF reports. The model is only one service inside this broader claims-evidence process. The backend must never translate an image score into an automatic rejection.")],
   ["<b>Input:</b> credentials, JSON, photos encoded as data URLs, claim details and staff actions.","<b>Processing:</b> validate, authenticate, authorize, call model code and update workflow data.","<b>Output:</b> safe JSON, session cookies, evidence reports and a review recommendation.","<b>Core rule:</b> the frontend can suggest; the backend must enforce."],None),
  ("2","Repository map and how to run the actual application",[
   ("Where to read first","The canonical project is vericlaim-ai. Start with <b>server.py</b>; it starts the HTTP server, loads the deployed model, serves frontend assets and dispatches API routes. Then read <b>src/vericlaim/model.py</b>, which turns images into model outputs."),
   ("Why the file layout matters","The design separates web/API orchestration from reusable ML code. Models are saved under models, feature extraction lives under src/vericlaim, and tests validate behaviour. This lets a backend engineer integrate a model without re-implementing training inside a web route.")],
   ["<b>server.py:</b> routes, JSON, sessions, validation, workflow and reports.","<b>src/vericlaim/model.py:</b> VeriClaimModel.load, analyze_image and score_claim.","<b>src/vericlaim/features.py:</b> image/forensic feature extraction.","<b>models/efficientnet_hybrid:</b> deployed artifact and evaluation outputs.","<b>tests:</b> feature, model and validation behaviour checks."],["Browser","server.py handler","vericlaim model module","saved artifact","JSON or PDF response"]),
  ("3","Your development loop: run, inspect, prove",[
   ("Start locally","Run server.py from the canonical project directory. The local app is served at port 8080. Use this running system as a learning tool: sign in, submit a controlled image, then inspect the exact request and response in the browser Network panel."),
   ("Avoid guesswork","When a UI looks wrong, do not assume CSS or the model is the cause. First inspect the API method, URL, HTTP status and returned JSON. The backend may have rejected input, the user may lack a session, or a frontend field may not match the response contract.")],
   ["<b>Start:</b> .venv\\Scripts\\python.exe server.py","<b>Open:</b> http://127.0.0.1:8080/","<b>Tests:</b> set PYTHONPATH=src; python -m unittest discover -s tests -v","<b>Browser DevTools:</b> Network shows method, payload, status and response.","<b>Work only in canonical code:</b> role-packet copies are reading aids, not the running app."],"# PowerShell\n$env:PYTHONPATH='src'\n.venv\\Scripts\\python.exe -m unittest discover -s tests -v\n.venv\\Scripts\\python.exe server.py"),
  ("4","HTTP, JSON and API contracts",[
   ("The conversation protocol","A browser sends an HTTP request: method, path, headers and sometimes a body. The server returns a status code, headers and body. VeriClaim serves static HTML/CSS/JS for screens, and JSON for application data. This predictable conversation is called an API."),
   ("A contract prevents integration failures","A JSON response is a promise. A frontend can safely render it only if field names and types are stable. Before changing risk_tier, image_results or a status shape, find where the UI uses it, write down the new response, then change frontend and backend together.")],
   ["<b>GET:</b> read-only endpoints such as health, session, portal and model card.","<b>POST:</b> actions such as login, draft save, Model Lab test, analyze and staff updates.","<b>200:</b> success. <b>400:</b> malformed client input. <b>401:</b> no signed-in user. <b>403:</b> wrong role. <b>404:</b> missing resource. <b>500:</b> unexpected failure.","<b>Design target:</b> error responses are easy for the frontend to show and safe for users to read."],"POST /api/model-test\nContent-Type: application/json\n\n{ \"image\": \"data:image/jpeg;base64,...\" }\n\n200 OK\n{ \"classification\": \"Review recommended\", \"risk_score\": 0.42, ... }"),
  ("5","Routes and handlers: how server.py responds",[
   ("Route dispatch","Handler extends Python's SimpleHTTPRequestHandler. Its do_GET and do_POST methods check self.path and choose a handler. A route is simply a named entry point such as /api/health, /api/analyze or /api/claims/<case_id>/status."),
   ("Keep routes thin","The route should parse, authorize and call a focused handler/service. It should not contain copied model mathematics or a large amount of unrelated logic. send_json provides a consistent response shape and read_json is the boundary for parsing request bodies.")],
   ["<b>send_json:</b> serializes a response and sets JSON headers consistently.","<b>read_json:</b> parses the body; reject malformed/empty bodies early.","<b>Route order:</b> check specific fixed paths before broad dynamic patterns.","<b>Dynamic paths:</b> regex matching supports case-specific routes.","<b>One purpose per endpoint:</b> makes documentation and testing clearer."],"def do_POST(self):\n    if self.path == '/api/model-test':\n        return self.handle_model_test()\n    if self.path == '/api/analyze':\n        return self.handle_analyze()\n    self.send_json({'error': 'Route not found'}, 404)"),
  ("6","Authentication: prove who is calling",[
   ("Passwords and login","Authentication answers “who is this caller?” In the demo, a user signs up/logs in with email and password. Passwords are stored as PBKDF2-derived records with random salt, not readable text. The server compares a newly derived record instead of reading a plain password back."),
   ("Session lifecycle","A successful login creates an opaque random session token. The server returns it as an HttpOnly, SameSite cookie. Later requests send the cookie automatically; current_user maps its token to a user record. A caller does not become staff merely by placing role: staff in JSON.")],
   ["<b>Salt:</b> makes identical passwords generate different stored records.","<b>PBKDF2:</b> deliberately slower password hashing to resist guessing.","<b>Opaque token:</b> random session identifier, not a password.","<b>HttpOnly cookie:</b> normal browser JavaScript cannot read it.","<b>Prototype limit:</b> sessions/users are in memory and disappear on restart."],["Login form","POST /api/auth/login","PBKDF2 verification","session cookie","current_user on later request"]),
  ("7","Authorization: customers and staff have different powers",[
   ("Authentication is not authorization","A signed-in user is identified, but still may not have permission to take a particular action. Authorization answers “may this person do this?” A customer must not view another customer's case just by editing a case ID in a URL."),
   ("The project guard","require_user(role) centralizes the check. With no valid session it returns 401. With the wrong role it returns 403. Customer-specific data needs an additional ownership filter using the current signed-in identity. Hiding staff navigation in the UI is never security by itself.")],
   ["<b>Customer:</b> their own claims, drafts, policies and permitted messages.","<b>Staff:</b> broader queue, status changes, reviewer feedback and reports.","<b>401:</b> not signed in; <b>403:</b> signed in but not permitted.","<b>Ownership:</b> always derive the owner from current_user, never request JSON.","<b>Audit:</b> production should record actor, time and before/after status."],"user = self.require_user(role='staff')\nif not user:\n    return  # guard already sent 401/403\n# It is now safe to perform staff-only work."),
  ("8","Safe image intake: evidence is untrusted input",[
   ("Data URL parsing","The browser passes uploaded photos as image data URLs: a MIME prefix plus base64 text. parse_data_url accepts image URLs, decodes base64 and checks MAX_IMAGE_BYTES. Do not trust a filename extension or client-supplied MIME label as proof that content is safe."),
   ("Why validation happens twice","Frontend validation gives immediate friendly feedback. Backend validation is the security boundary: a malicious or curious caller can skip all browser controls and call POST directly. The backend must enforce every important rule again.")],
   ["<b>Current limits:</b> 1 to 8 images per claim; 10 MB maximum per image.","<b>Fail early:</b> reject oversized/bad data before costly inference.","<b>Data URL trade-off:</b> convenient for a demo, but large base64 payloads use memory.","<b>Production:</b> presigned object-storage upload, file sniffing, malware scan, EXIF policy and rate limits.","<b>Privacy:</b> never put raw base64 image content in ordinary logs."],["User selects image","frontend creates data URL","parse_data_url decodes","limits/type checks","model receives bytes"]),
  ("9","Concurrency and the prototype's in-memory state",[
   ("Why the server has a LOCK","ThreadingHTTPServer can serve several requests concurrently. The demo stores USERS, SESSIONS, DRAFTS, MESSAGES and NOTIFICATIONS in Python dictionaries/lists. Without care, two request threads can modify a structure at the same time and cause inconsistent results."),
   ("How to use a lock properly","LOCK surrounds small critical sections that read or change shared memory. Acquire it, make the smallest necessary change, then release it. Never hold it while doing slow model inference, PDF generation or future network calls because other requests would be blocked.")],
   ["<b>Good lock scope:</b> locate/modify one shared record, then release.","<b>Bad lock scope:</b> hold global lock around an entire image analysis request.","<b>Restart behaviour:</b> all in-memory state is lost; this is expected in the demo.","<b>Scaling limitation:</b> separate Python processes do not share this memory.","<b>Production:</b> database transactions, durable sessions and object storage replace in-process state."],None),
  ("10","Model integration: inference is not training",[
   ("Load once at startup","MODEL_PATH selects the deployed artifact. VeriClaimModel.load reads it once when server.py starts. Requests reuse the loaded object. This is inference: applying learned parameters to a new image. Training happened earlier, offline, with labeled data and leakage-aware validation."),
   ("Two model methods","analyze_image creates an image-level result. score_claim combines one or more image results into a claim-level triage response. This allows the UI to show individual evidence rather than hiding every photo inside one opaque score.")],
   ["<b>Do not retrain in a request:</b> training is expensive, non-deterministic and needs controlled data governance.","<b>Model output:</b> a calibrated risk signal, not a proof or legal finding.","<b>Per-image result:</b> useful for evidence and explanation.","<b>Claim score:</b> routes a case for human review using all submitted evidence.","<b>Failure policy:</b> return safe service error; preserve intake for later review."],["Raw bytes","feature extraction","hybrid prediction","calibrated probability","human review route"]),
  ("11","The hybrid model: what the backend receives",[
   ("Signals, not magic","The deployed saved pipeline combines visual information with other signals. EfficientNetV2B0 contributes a CNN visual probability. Extra Trees and MLP components work on extracted feature vectors. Perceptual-hash archive similarity supports possible image-reuse investigation. Calibration makes a raw score more meaningful as a probability."),
   ("What to say honestly","Quality, similarity or an unusual visual pattern may justify review. They are not proof of fraud. The backend returns contributing factors and a human-decision policy so the product does not pretend that a neural network knows intent.")],
   ["<b>CNN:</b> learns visual patterns from labelled images.","<b>Extra Trees/MLP:</b> learn relationships in numerical features.","<b>Archive similarity:</b> supports duplicate/reuse detection via perceptual hash patterns.","<b>Calibration:</b> improves reliability of probability estimates.","<b>Threshold:</b> maps score to review priority; choose it using validation evidence."],None),
  ("12","Claim scoring and human-led triage",[
   ("Several photos, one case","A claim can contain multiple views. A simple average can wrongly dilute one suspicious image with several normal ones. The model's score_claim logic uses image-level results and returns a case-level tier, factor list and review guidance. The frontend should consume this result rather than repeat model logic in JavaScript."),
   ("Score versus decision","A numerical score is a model estimate. A tier is a workflow-friendly grouping. A claim decision is a human insurance decision after relevant evidence and policy review. Maintaining these separate concepts is both technically and ethically important.")],
   ["<b>Low tier:</b> lower review priority, not a guarantee of legitimacy.","<b>Medium tier:</b> verify context and evidence.","<b>High tier:</b> prioritize staff review; it is not automatic rejection.","<b>Claim amount:</b> contextual triage input, never a hidden unfairness proxy.","<b>Factors:</b> explain categories of evidence, not imagined human reasoning."],"image_results = [MODEL.analyze_image(raw) for raw in images]\ntriage = MODEL.score_claim(image_results, claim_amount=amount)\nresponse = {'images': image_results, 'triage': triage,\n            'decision_policy': 'Human review required'}"),
  ("13","API contracts for VeriClaim screens",[
   ("Contract worksheet mindset","For every endpoint write its purpose, route, method, authentication requirement, JSON request, response, errors and side effects. This protects frontend/backend integration. It also makes reviewers see that the project is engineered as a system, not only as a model demo."),
   ("Keep Model Lab isolated","POST /api/model-test exists for one-image experiments. It should not create a formal claim. POST /api/analyze is the claim-workflow route, so it performs broader validation and produces a case record. This separation protects both user experience and demo clarity.")],
   ["<b>GET /api/health:</b> readiness check.","<b>GET /api/session:</b> current user without password data.","<b>POST /api/auth/login:</b> identity -> session lifecycle.","<b>POST /api/drafts:</b> auto-save, still revalidate on final submit.","<b>POST /api/model-test:</b> isolated Model Lab analysis.","<b>POST /api/analyze:</b> evidence -> triage + claim workflow.","<b>Staff routes:</b> status/feedback/report require staff role."],None),
  ("14","Build a new endpoint safely: worked example",[
   ("Start with a contract","Imagine a user asks for “mark notification read.” Before editing UI, decide the exact method/path, who can call it, how ownership is checked, what changes and what response comes back. A clear contract makes code short and testable."),
   ("Implementation order","Add a precise route match. Call require_user. Validate the notification ID. Under LOCK, find only a notification belonging to the current user and update it. Return the revised public object. Then test the success case and every denial case.")],
   ["<b>1:</b> POST /api/notifications/&lt;id&gt;/read; signed-in owner required.","<b>2:</b> reject malformed/unknown IDs with 400/404.","<b>3:</b> do not accept owner email from the client.","<b>4:</b> lock only for shared state mutation.","<b>5:</b> test signed-out, wrong owner, valid owner and repeated request.","<b>6:</b> update frontend contract and endpoint documentation."],"def handle_notification_read(self, notification_id):\n    user = self.require_user()\n    if not user: return\n    with LOCK:\n        item = find_owned_notification(notification_id, user['email'])\n        if not item: return self.send_json({'error':'Not found'}, 404)\n        item['read'] = True\n    self.send_json({'notification': item})"),
  ("15","Claims workflow, messaging and PDF evidence reports",[
   ("The model is not the entire product","A useful insurance experience includes drafts, claim status, communication, reports and staff review. The backend ties these pieces together. A model score becomes valuable only when it arrives in an understandable workflow for a real investigator or customer."),
   ("Feedback is not instant retraining","Staff feedback can be collected as a future evaluation signal. It should not automatically retrain or alter a deployed model, because feedback must be curated, labels checked and performance re-evaluated before promotion.")],
   ["<b>Draft:</b> partial customer input; validate again on final submission.","<b>Message:</b> linked to a case; enforce participant/role access.","<b>Status:</b> explicit human workflow state such as submitted, under review or settled.","<b>Report/receipt:</b> readable evidence record, not autonomous adverse decision.","<b>Feedback:</b> future governance/evaluation signal."],["Customer submits","case record","model triage assists","staff review","status/message/report"]),
  ("16","Errors, logging and a debugging method",[
   ("Expected versus unexpected failures","Malformed JSON, missing evidence, invalid image data, missing session and unknown case IDs are expected client errors. Return clear 4xx responses. An unexpected model or code exception is a 5xx incident; do not expose stack traces, model paths, passwords, session tokens or raw image data in the response."),
   ("Debug in the right order","Start with browser Network evidence: endpoint, payload, status and JSON. Then inspect server logs. Only after confirming the API behaviour should you change frontend rendering or investigate model output. This avoids treating symptoms instead of causes.")],
   ["<b>Useful logs:</b> time, route, request/case ID, status, latency, role, model version and triage tier.","<b>Never log:</b> passwords, session tokens or base64 evidence payloads.","<b>400:</b> invalid client request; tell user how to recover.","<b>401/403:</b> missing session or permission failure.","<b>500:</b> safe generic message to user; detailed diagnostic in protected log."],None),
  ("17","Testing: prove the backend works safely",[
   ("Existing tests","The project includes tests for features, model logic and validation. Preserve them. Add route-level tests whenever you change web behaviour. A screen loading is not proof that authorization, validation and error handling are correct."),
   ("Make tests deterministic","Do not depend on a random real-photo score to test an API route. Test routes with controlled inputs or a mock model boundary. Evaluate actual model performance separately with the documented leakage-aware validation pipeline.")],
   ["<b>Unit:</b> one function, e.g. data URL rejection.","<b>Integration:</b> route + handler + model-service interface.","<b>Authorization:</b> customer cannot update other user's case; non-staff gets 403.","<b>Regression:</b> every fixed bug gets a test.","<b>Smoke test:</b> start, sign in, submit controlled evidence, view result and download report."],"# Minimum route test matrix\n1. Valid request -> 200 + expected JSON schema\n2. Missing/invalid JSON -> 400\n3. No session -> 401\n4. Wrong role -> 403\n5. Unknown case -> 404\n6. Model exception -> safe 5xx; no traceback exposed"),
  ("18","Security, privacy and fairness boundaries",[
   ("A chain of controls","Insurance evidence can contain personal and vehicle information. Security is not only login. It includes input validation, server-side permissions, protected sessions, limited logging, private report access, secret management, durable audit events and secure deployment."),
   ("Be accurate about the demo","The local standard-library HTTP server and in-memory structures are suitable for a transparent hackathon prototype. They are not an insurer's final architecture. Saying exactly how you would evolve them demonstrates engineering maturity.")],
   ["<b>Input:</b> limits, decoding checks, file policy and safe errors.","<b>Identity:</b> password hashing, secure cookies, HTTPS and rate limits.","<b>Access:</b> role and ownership checks on every protected resource.","<b>Data:</b> no secrets in Git; encrypt durable data and restrict storage access.","<b>Fairness:</b> AI triage never solely determines adverse action; monitor overrides and performance."],None),
  ("19","Production architecture and deployment evolution",[
   ("Why the architecture changes","The present design is easy to run for a demo. Production needs durable data, private evidence storage, multiple users, observability, reliable scaling and controlled model releases. Evolve components gradually rather than rewriting the entire application at once."),
   ("A sensible target","Run a stateless API behind a gateway. Let customers upload evidence directly to private object storage with controlled URLs. Store claims and workflow events in PostgreSQL. Put heavy analysis/report generation on a queue worker. Version models and record the model/threshold used for each triage event.")],
   ["<b>API:</b> FastAPI/equivalent behind HTTPS reverse proxy or API gateway.","<b>Evidence:</b> object storage + presigned uploads + retention policy.","<b>Workflow:</b> PostgreSQL migrations and audit events.","<b>Heavy work:</b> queue/worker for image inspection and PDFs.","<b>Model operations:</b> versioned artifacts, controlled promotion, telemetry and rollback.","<b>Deployment:</b> Docker, secrets manager, health checks and CI tests."],["Browser","API gateway + auth","object storage / database","queue + model worker","staff portal + audit"]),
  ("20","Four-week mastery plan and presentation answers",[
   ("A realistic study order","Week 1: run server.py and trace simple GET/POST routes. Week 2: trace signup/login, cookie session and customer/staff ownership. Week 3: trace an image from data URL through analysis to triage. Week 4: add one small safe endpoint with tests, then explain the production migration."),
   ("Answer a reviewer confidently","Lead with purpose: VeriClaim is a human-led evidence and fraud-triage system. The backend protects data, validates evidence, integrates the model and presents its signals inside a claims workflow. The project does not claim that an AI can autonomously prove fraud.")],
   ["<b>Request path:</b> browser -> route -> validation/auth -> model/workflow -> JSON -> UI.","<b>Security boundary:</b> frontend checks improve usability; backend checks enforce safety.","<b>Model boundary:</b> calibrated risk signal; staff retains final authority.","<b>Prototype gap:</b> in-memory demo now; DB/storage/queue/audit path for production.","<b>Release checklist:</b> tests, invalid uploads, customer/staff boundaries, model failure, safe logs and recorded model version."],None)
  ]
  for n,title,sections,points,extra in chapters:
    story += chapter(n,title)
    for heading,body in sections: story += section(heading,body)
    story += [P("What to remember",ss["BTH2"])] + bullets(points)
    if isinstance(extra,list): story += [Spacer(1,5),diagram(extra,ss)]
    if isinstance(extra,str): story += [Spacer(1,5),code(extra,ss)]
    story += [PageBreak()]
  story += chapter("Appendix A","API contract worksheet")
  story += [P("Use this template before adding or changing an endpoint. It prevents frontend/backend integration surprises.",ss["BTBody"])]
  rows=[[P(x,ss["BTFlow"]) for x in ["Field","Write this before coding"]],
        [P("Purpose",ss["BTBody"]),P("What user problem does this solve?",ss["BTBody"])],[P("Method/path",ss["BTBody"]),P("GET or POST? Exact route?",ss["BTBody"])],[P("Auth",ss["BTBody"]),P("Public, signed-in owner or staff-only?",ss["BTBody"])],[P("Request",ss["BTBody"]),P("Required fields, types, size limits and validation.",ss["BTBody"])],[P("Response",ss["BTBody"]),P("Exact JSON fields, types and error shape.",ss["BTBody"])],[P("Side effects",ss["BTBody"]),P("What changes and what should be audited?",ss["BTBody"])],[P("Tests",ss["BTBody"]),P("Success, invalid input, no session, wrong role, wrong owner, not found.",ss["BTBody"])]]
  story += [Table(rows,colWidths=[4*cm,13*cm],style=TableStyle([("BACKGROUND",(0,0),(-1,0),colors.HexColor("#dceee1")),("GRID",(0,0),(-1,-1),.4,colors.HexColor("#a9c7b3")),("VALIGN",(0,0),(-1,-1),"TOP"),("LEFTPADDING",(0,0),(-1,-1),7),("RIGHTPADDING",(0,0),(-1,-1),7),("TOPPADDING",(0,0),(-1,-1),7),("BOTTOMPADDING",(0,0),(-1,-1),7)])),PageBreak()]
  story += chapter("Appendix B","Glossary")
  glossary=[("API","Planned interface through which software requests data/action."),("Artifact","Saved trained model parameters/configuration used for prediction."),("Authentication","Proving a caller's identity."),("Authorization","Checking whether an identified caller may act."),("Calibration","Aligning predicted probabilities more closely with observed outcomes."),("Data URL","String containing base64-encoded file content used by the demo for uploads."),("Inference","Using a trained model on new input."),("PBKDF2","Slow password-hashing method that helps resist guessing."),("RBAC","Role-based access control."),("Triage","Prioritising work for human review, not an automated final decision.")]
  for term,meaning in glossary: story += [P(term,ss["BTH2"]),P(meaning,ss["BTBody"])]
  story += [P("<b>Final self-check:</b> If you can explain why images are validated twice, why a hidden staff button is not security, why a model score is not a verdict, and how the local demo becomes a durable workflow system, you understand the core VeriClaim backend.",ss["BTCallout"])]
  def foot(c,d):
    c.saveState(); c.setStrokeColor(colors.HexColor("#b8d6c2")); c.line(1.8*cm,1.6*cm,19.2*cm,1.6*cm); c.setFont("Helvetica",8); c.setFillColor(colors.HexColor("#426457")); c.drawString(1.8*cm,1.15*cm,"VeriClaim AI - Backend Engineer Master Guide"); c.drawRightString(19.2*cm,1.15*cm,f"Page {d.page}"); c.restoreState()
  SimpleDocTemplate(str(OUT),pagesize=A4,leftMargin=1.8*cm,rightMargin=1.8*cm,topMargin=1.7*cm,bottomMargin=2.1*cm,title="VeriClaim AI Backend Engineer Master Guide").build(story,onFirstPage=foot,onLaterPages=foot)
  print(OUT)
if __name__=="__main__": build()
